package millbuild

import mill.*

import scala.collection.mutable

/** Generates the `eu.neverblink.linkml.tests.ModelCatalogueEntries` trait, which `ModelCatalogue`
  * extends, with an entry for every `model.yaml` under `/models/` in the resources.
  *
  * The entries are nested like the directories of the models, so `/models/inlines/explicitInline/`
  * becomes `ModelCatalogue.inlines.explicitInline`. The entries are read from the `Resources`
  * generated by [[ResourcesAsStrings]].
  */
trait ModelCatalogueEntries extends ResourcesAsStrings {
  override def generatedSources = Task {
    val modelDirs = ResourcesAsStrings.files(resources()).collect {
      case ("models" +: segments, _) if segments.lastOption.contains("model.yaml") => segments.init
    }
    val dest = Task.dest / "eu" / "neverblink" / "linkml" / "tests" / "ModelCatalogueEntries.scala"
    os.write.over(dest, ModelCatalogueEntries.generate(modelDirs), createFolders = true)
    super.generatedSources() :+ PathRef(dest)
  }
}

object ModelCatalogueEntries {

  /** Members of `ModelCatalogue`, which can't be names of models */
  private val reserved =
    Set("all", "allOptIn", "Entry", "Format", "InstanceInFormats", "path", "inFormat", "hasFormat")

  private val pkg = "_root_.eu.neverblink.linkml.tests"

  private case class Group(segments: Seq[String]) {
    val models = mutable.ArrayBuffer.empty[Seq[String]]
    val groups = mutable.ArrayBuffer.empty[Group]
  }

  /** @param modelDirs
    *   path segments of the directories of the models, relative to `/models/`
    */
  def generate(modelDirs: Seq[Seq[String]]): String = {
    val modelSet = modelDirs.toSet
    val root = Group(Nil)
    val groups = mutable.LinkedHashMap[Seq[String], Group](Nil -> root)
    def groupOf(segments: Seq[String]): Group = groups.getOrElseUpdate(
      segments, {
        if (modelSet(segments))
          sys.error(
            s"The model in /models/${segments.mkString("/")}/ has models in sub-directories",
          )
        val group = Group(segments)
        groupOf(segments.init).groups += group
        group
      },
    )
    modelDirs.foreach { segments =>
      if (segments.isEmpty || segments.exists(reserved) || segments.exists(_.contains('`')))
        sys.error(s"Can't generate an entry for the model in /models/${segments.mkString("/")}/")
      groupOf(segments.init).models += segments
    }

    def ref(segments: Seq[String]): String = segments.map(ResourcesAsStrings.ident).mkString(".")

    val sb = new java.lang.StringBuilder
    sb.append(
      "// Generated by ModelCatalogueEntries from the resources of the module. Do not edit.\n",
    )
    sb.append("package eu.neverblink.linkml.tests\n")
    sb.append(
      "\n/** An entry of [[ModelCatalogue]] for every model in `/models/` of the resources */\n",
    )
    sb.append("trait ModelCatalogueEntries {\n")
    def members(group: Group, indent: String): Unit = {
      group.models.foreach { segments =>
        sb.append(s"\n$indent/** /models/${segments.mkString("/")}/ */\n")
        sb.append(
          s"${indent}lazy val ${ResourcesAsStrings.ident(segments.last)}: $pkg.ModelCatalogue.Entry =\n",
        )
        sb.append(
          s"$indent  $pkg.ModelCatalogue.Entry($pkg.Resources.models.${ref(segments)}.path)\n",
        )
      }
      group.groups.foreach { sub =>
        sb.append(s"\n${indent}object ${ResourcesAsStrings.ident(sub.segments.last)} {\n")
        members(sub, indent + "  ")
        sb.append(s"$indent}\n")
      }
    }
    members(root, "  ")
    sb.append("\n  /** All model catalogue entries, including those with the opt_in flag set */\n")
    sb.append(s"  lazy val allOptIn: Seq[$pkg.ModelCatalogue.Entry] = Seq(\n")
    modelDirs.foreach(segments => sb.append(s"    ${ref(segments)},\n"))
    sb.append("  )\n")
    sb.append("}\n")
    sb.toString
  }
}
