package eu.neverblink.linkml.generator.scala

import eu.neverblink.linkml.schemaview.Case
import eu.neverblink.linkml.tests.{ModelCatalogue, ModelCatalogueSpec}
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec

import java.net.URLClassLoader

/** Round-trips the catalogue's instance data through the code generated by [[ScalaGenerator]].
  *
  * For every model this generates the Scala sources, compiles them together with a small driver
  * that derives a [[eu.neverblink.linkml.yaml.LinkmlYamlCodec]] for the tree root, and then decodes
  * each valid `data.json` with it.
  *
  * JVM-only: it needs the Scala compiler.
  */
class ScalaCodecRoundTripSpec extends AnyWordSpec, Matchers, ModelCatalogueSpec {
  override val skipModels: Map[String, String] =
    ScalaGeneratorCompileSpec.skipModels ++ Map(
      "typeDesignator" -> noDispatchingCodec,
      "typeDesignator2" -> noDispatchingCodec,
      "typed" -> noCodecForType("decimal", "date"),
      "constraints" -> noCodecForType("float"),
      "constraintsOnTypes" -> noCodecForType("float"),
    )

  override val skipInstances: Map[(String, String), String] = Seq(
    "uri",
    "curie",
    "uriOrCurie",
  ).map(model =>
    (model, "empty") ->
      "an instance with no slots set encodes to an empty document, which cannot be parsed back",
  ).toMap

  private def noDispatchingCodec: String =
    "LNK-187: the typeDesignator codec is not auto-derived"

  private def noCodecForType(types: String*): String =
    s"LinkmlYamlCodec cannot be derived for the ${types.mkString(" and ")} " +
      s"${if types.size == 1 then "range" else "ranges"}: the codec only covers string, int and " +
      "boolean scalars, so the generated class has a field it has no codec for"

  /** Compiles a model's generated sources plus a driver exposing the tree root's codec, and returns
    * a `(decode, encode)` pair bound to it.
    *
    * @return
    *   Left with the reason to skip
    */
  private def driverFor(
      entry: ModelCatalogue.Entry,
  ): Either[String, (String => AnyRef, AnyRef => String)] = {
    val treeRoot = entry.model.treeRoot match {
      case Some(tr) => tr
      case _ => return Left("the model has no tree root")
    }
    if treeRoot.cls.`abstract` || treeRoot.cls.mixin then
      return Left("the tree root is abstract, so no implementation is generated for it")
    if treeRoot.attributeViews.sizeIs == 1 then
      return Left(
        "the codec writes a class that has a single slot as a bare value rather than as an " +
          "object, so it cannot read the object form that the catalogue's data.json uses",
      )
    val rootImpl = s"${Case.PascalCase(treeRoot.cls.name)}Impl"

    val dir = os.temp.dir(prefix = "linkml-roundtrip-src")
    val sources = ScalaGenerator(using entry.model).generate(ScalaGenerator.Options("generated"))
      .map { (name, content) =>
        val file = dir / name
        os.write(file, content)
        file
      }.toSeq
    val driver = dir / "RoundTripDriver.scala"
    os.write(
      driver,
      s"""package generated
         |
         |import eu.neverblink.linkml.yaml.LinkmlYamlCodec
         |import org.virtuslab.yaml.*
         |
         |object RoundTripDriver {
         |  private val codec: LinkmlYamlCodec[$rootImpl] = LinkmlYamlCodec.derived
         |
         |  def decode(input: String): AnyRef =
         |    codec.decode(parseYaml(input).toOption.get).asInstanceOf[AnyRef]
         |
         |  def encode(x: AnyRef): String = codec.encode(x.asInstanceOf[$rootImpl]).asYaml
         |}
         |""".stripMargin,
    )

    val out = os.temp.dir(prefix = "linkml-roundtrip-out")
    val log = java.io.ByteArrayOutputStream()
    val args = Array("-classpath", System.getProperty("java.class.path"), "-d", out.toString) ++
      (sources :+ driver).map(_.toString)
    val reporter =
      Console.withErr(log)(Console.withOut(log)(dotty.tools.dotc.Driver().process(args)))
    withClue(s"compiler output:\n$log\n")(reporter.hasErrors shouldBe false)

    val loader = URLClassLoader(Array(out.toNIO.toUri.toURL), getClass.getClassLoader)
    val module = loader.loadClass("generated.RoundTripDriver$").getField("MODULE$").get(null)
    val decodeM = module.getClass.getMethod("decode", classOf[String])
    val encodeM = module.getClass.getMethod("encode", classOf[AnyRef])
    // Reflection wraps whatever the codec throws, which would otherwise hide the real failure.
    def unwrapped[A](f: => A): A =
      try f
      catch { case e: java.lang.reflect.InvocationTargetException => throw e.getCause }
    Right(
      (
        s => unwrapped(decodeM.invoke(module, s)),
        x => unwrapped(encodeM.invoke(module, x).asInstanceOf[String]),
      ),
    )
  }

  "Generated Scala" should {
    for entry <- ModelCatalogue.all if entry.validInstances.exists(_.json.isDefined) do
      s"round-trip instances of model '${entry.name}'" when {
        lazy val driver = driverFor(entry)

        for valid <- entry.validInstances.filter(_.json.isDefined).distinct do
          s"valid instance '${valid.name}'" in {
            processSkip(entry, valid)
            driver match {
              case Left(reason) => cancel(reason)
              case Right((decode, encode)) =>
                val decoded = decode(valid.json.get)
                withClue(s"re-encoded as:\n${encode(decoded)}\n") {
                  decode(encode(decoded)) shouldBe decoded
                }
            }
          }
      }
  }
}
