// Generated by LinkML-Scala from https://w3id.org/linkml/conformance/
// DO NOT EDIT.

package eu.neverblink.linkml.tests.conformance

import eu.neverblink.linkml.runtime.*

/** The implementation should run the schema derivation procedure as defined in the specification,
  * serialize the derived schema, and pass the serialized schema as the Action result.
  *
  * @param description
  *   Description of an element, including the implementation guide
  * @param title
  *   Human readable name of an element
  * @see
  *   From schema: https://w3id.org/linkml/conformance/
  */
final case class DeriveAction(
    description: Option[String] = None,
    title: Option[String] = None,
    @named("type")
    @serializeDefault
    `type`: Option[String] = Some("DeriveAction"),
) extends Action {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): DeriveAction =
    this
}
