// Generated by LinkML-Scala from https://w3id.org/linkml/conformance/
// DO NOT EDIT.

package eu.neverblink.linkml.tests.conformance

import eu.neverblink.linkml.runtime.*

/** An implementation of this assertion must load the result of an Action as a YAML document, and
  * then dereference a JSON pointer provided in the 'path' attribute and compare it against the
  * 'value'.
  *
  * @param description
  *   Description of an element, including the implementation guide
  * @param path
  *   The JSON pointer that will be dereferenced.
  * @param title
  *   Human readable name of an element
  * @param value
  *   The expected value to be found after dereferencing the JSON pointer.
  * @see
  *   From schema: https://w3id.org/linkml/conformance/
  */
final case class JsonPointerAssertion(
    description: Option[String] = None,
    path: String,
    title: Option[String] = None,
    @named("type")
    @serializeDefault
    `type`: Option[String] = Some("JsonPointerAssertion"),
    value: LinkmlAny,
) extends Assertion {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): JsonPointerAssertion =
    this
}
