// Generated by LinkML-Scala from https://w3id.org/linkml/conformance/
// DO NOT EDIT.

package eu.neverblink.linkml.tests.conformance

import eu.neverblink.linkml.runtime.*

/** An implementation of this assertion must load the result of an Action into an appropriate
  * internal data structure. Should the process fail, the assertion fails.
  *
  * @param description
  *   Description of an element, including the implementation guide
  * @param title
  *   Human readable name of an element
  * @see
  *   From schema: https://w3id.org/linkml/conformance/
  */
final case class LoadsAssertion(
    description: Option[String] = None,
    title: Option[String] = None,
    @named("type")
    @serializeDefault
    `type`: Option[String] = Some("LoadsAssertion"),
) extends Assertion {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): LoadsAssertion =
    this
}
