// Generated by LinkML-Scala from https://w3id.org/linkml/conformance/
// DO NOT EDIT.

package eu.neverblink.linkml.tests.conformance

import eu.neverblink.linkml.runtime.*

/** An implementation of this assertion must load the result of an Action as a string, then, for
  * each value in 'includes', it must check that the value is a substring of the result of an
  * Action, failing if any of the strings are not present. Should 'includes' be empty, the assertion
  * should pass.
  *
  * @param description
  *   Description of an element, including the implementation guide
  * @param title
  *   Human readable name of an element
  * @see
  *   From schema: https://w3id.org/linkml/conformance/
  */
final case class StringAssertion(
    description: Option[String] = None,
    includes: Seq[String] = Seq(),
    title: Option[String] = None,
    @named("type")
    @serializeDefault
    `type`: Option[String] = Some("StringAssertion"),
) extends Assertion {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): StringAssertion =
    this
}
