// Generated by LinkML-Scala from https://w3id.org/linkml/conformance/
// DO NOT EDIT.

package eu.neverblink.linkml.tests.conformance

import eu.neverblink.linkml.runtime.*

/** A single test consisting of a schema, action, and assertion
  *
  * @param description
  *   Description of an element, including the implementation guide
  * @param title
  *   Human readable name of an element
  * @see
  *   From schema: https://w3id.org/linkml/conformance/
  */
final case class Test(
    action: Action,
    assertion: Assertion,
    description: Option[String] = None,
    @id
    name: String,
    schema: String,
    title: Option[String] = None,
) {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  def infer(): Test =
    this
}
