// Generated by linkml-scala from https://linkml.neverblink.eu/model/build-info. Do not edit.

/** Build info: Version and build metadata of the LinkML-Scala distribution that produced this report. */
export interface BuildInfo {
  /** ABI version: The version of the C ABI exported by the shared library, matching what `linkml_abi_version` returns. Present in the native library and its Python bindings only. */
  abi_version?: number;
  /** LinkML-Scala version: The SemVer version of LinkML-Scala itself. Releases are plain versions like `1.2.3`. Builds made between releases include the commit they were built from, like `1.2.3-4-abcdef1-SNAPSHOT`. */
  linkml_scala_version: string;
  /** metamodel version: The version of the LinkML metamodel this distribution was built against, taken from `metamodel_version` in the LinkML `meta` schema. */
  metamodel_version: string;
  /** platform: The kind of build this is, and therefore which of the optional slots can appear. */
  platform: Platform;
  /** runtime: Human-readable description of the virtual machine or engine currently executing the code, for example `OpenJDK 64-Bit Server VM 25.0.1` or `Node.js v24.2.0`. Useful for bug reports. */
  runtime?: string;
  /** Scala.js version: The version of Scala.js this distribution was compiled with. JavaScript builds only. */
  scala_js_version?: string;
  /** Scala version: The version of the Scala compiler this distribution was built with. */
  scala_version: string;
}

/** Platform: The kind of build a LinkML-Scala distribution is. */
export type Platform =
  | "JVM"
  | "NATIVE"
  | "SCALA_NATIVE"
  | "JS";
