// Generated by linkml-scala from https://linkml.neverblink.eu/model/issue-types. Do not edit.

/**
 * Code region: A region of code in a schema where an issue was found.
 * This class is a simplified (special case) version of the `region` object from the SARIF specification:
 * https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790935
 *
 * Indexing is 1-based.
 */
export interface CodeRegion {
  /** end column: The column number in the schema where the issue ends (1-based, EXCLUSIVE). */
  end_column?: number;
  /** end line: The line number in the schema where the issue ends (1-based, inclusive). */
  end_line?: number;
  /** start column: The column number in the schema where the issue starts (1-based). */
  start_column: number;
  /** start line: The line number in the schema where the issue starts (1-based). */
  start_line: number;
}

/** An element has an empty name after renaming */
export interface EmptyName {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** element name: Name of the element the issue was found in. */
  element_name: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "EmptyName";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
  /** used for: Formatted description of the elements that share the name. */
  transformed_name: string;
}

/** An element starts or ends with a word separator. This is reserved and may become an error in the future. */
export interface FlankingSeparator {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** element name: Name of the element the issue was found in. */
  element_name: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "FlankingSeparator";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** A slot omits its `range` while no usable `default_range` exists. */
export interface InvalidDefaultRange {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "InvalidDefaultRange";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** A `key` or `identifier` slot has a range that is not a scalar type. */
export interface InvalidKeyOrIdSlotType {
  /** class name: Name of the class the issue was found in. */
  class_name: string;
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** element name: Name of the element the issue was found in. */
  element_name: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "InvalidKeyOrIdSlotType";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** A `range` points at an element that cannot be used as a range. */
export interface InvalidRange {
  /** actual type: The metamodel type the range actually resolved to. */
  actual_type: string;
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "InvalidRange";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** range value */
  range_value: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** A class declares `slot_usage` for slots that none of its ancestors provide. */
export interface InvalidSlotUsage {
  /** class name: Name of the class the issue was found in. */
  class_name: string;
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "InvalidSlotUsage";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
  /** slot names */
  slot_names: string[];
}

/** A URI or CURIE value in the schema is not a valid URI or `prefix:localname` pair. */
export interface InvalidUriOrCurie {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "InvalidUriOrCurie";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
  /** URI or CURIE */
  uri_or_curie: string;
}

/** Issue location: A location in a schema where an issue was found. */
export interface IssueLocation {
  /** code region: A region of code in the schema where the issue was found. */
  code_region?: CodeRegion;
  /** JSON pointer: A JSON pointer to the location in the schema where the issue was found. */
  json_pointer?: string;
  /** schema identifier: The identifier of the schema in which the issue was found. Always present, unless the issue pertains to the lack of the identifier itself. */
  schema_id?: string;
}

/** A class has more than one `key` or `identifier` slot. */
export interface MultipleKeyOrIdSlots {
  /** class name: Name of the class the issue was found in. */
  class_name: string;
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "MultipleKeyOrIdSlots";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
  /** slot names */
  slot_names: string[];
}

/** More than one class in the root schema is marked as `tree_root`. */
export interface MultipleTreeRoots {
  /** class names */
  class_names: string[];
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "MultipleTreeRoots";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** No class in the root schema is marked as `tree_root`. */
export interface NoTreeRootClass {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "NoTreeRootClass";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** An element name uses non-ASCII characters. */
export interface NonAsciiName {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** element name: Name of the element the issue was found in. */
  element_name: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "NonAsciiName";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** An element contains allowed, but non-standard word separators. This may become an error in the future. */
export interface NonStandardSeparator {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** element name: Name of the element the issue was found in. */
  element_name: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "NonStandardSeparator";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** Non-standards separators used */
  separators?: string[];
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** There is a name clash after name mangling */
export interface NonUniqueName {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** element name: Name of the element the issue was found in. */
  element_name: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "NonUniqueName";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
  /** used for: Formatted description of the elements that share the name. */
  transformed_name: string;
  /** used for: Formatted description of the elements that share the name. */
  used_for: string;
}

/** An element starts with a word separator. This may become an error in the future. */
export interface RepeatedSeparator {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** element name: Name of the element the issue was found in. */
  element_name: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "RepeatedSeparator";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

export type SchemaError =
  | EmptyName
  | InvalidKeyOrIdSlotType
  | InvalidUriOrCurie
  | MultipleKeyOrIdSlots
  | MultipleTreeRoots
  | NonAsciiName
  | NonUniqueName
  | UndefinedPrefix;

export type SchemaFatal =
  | InvalidDefaultRange
  | InvalidRange
  | SchemaIdClash
  | SchemaImportError
  | SchemaParseError
  | UnexpectedError
  | UnknownReference
  | UnknownStringReference;

/** Two distinct schemas declare the same `id`. */
export interface SchemaIdClash {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "SchemaIdClash";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** An imported schema could not be read. */
export interface SchemaImportError {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** import URI */
  import_uri: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "SchemaImportError";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** reason: Verbatim message from whatever failed to supply the schema text. */
  reason: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** Schema issue: A single issue found during the validation of a LinkML schema. */
export type SchemaIssue =
  | EmptyName
  | FlankingSeparator
  | InvalidDefaultRange
  | InvalidKeyOrIdSlotType
  | InvalidRange
  | InvalidSlotUsage
  | InvalidUriOrCurie
  | MultipleKeyOrIdSlots
  | MultipleTreeRoots
  | NoTreeRootClass
  | NonAsciiName
  | NonStandardSeparator
  | NonUniqueName
  | RepeatedSeparator
  | SchemaIdClash
  | SchemaImportError
  | SchemaParseError
  | UndefinedDefaultRange
  | UndefinedPrefix
  | UnexpectedError
  | UnknownReference
  | UnknownStringReference;

/** The schema text could not be parsed as YAML, or could not be decoded into the LinkML metamodel. Where the underlying parser reported a position, it is carried in `location.code_region`. */
export interface SchemaParseError {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "SchemaParseError";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** parser message: Verbatim message from the YAML parser or the metamodel decoder. */
  parser_message: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
  /** source URI: URI the schema text came from. Empty when parsing an in-memory string. */
  source_uri: string;
}

/** Schema validation report: A report of the validation of a LinkML schema. */
export interface SchemaValidationReport {
  /** issues: A list of issues found during the validation of the schema. */
  issues: SchemaIssue[];
  /** validation run identifier: Implementation-specific identifier of this validation run. This can be, for example, the top-level file name of the schema being validated. It is useful for multi-schema (batch) validation runs. */
  validation_run_id?: string;
}

export type SchemaWarning =
  | FlankingSeparator
  | InvalidSlotUsage
  | NoTreeRootClass
  | NonStandardSeparator
  | RepeatedSeparator
  | UndefinedDefaultRange;

/** The schema has no `default_range` and no `string` type to fall back on. */
export interface UndefinedDefaultRange {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "UndefinedDefaultRange";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** A prefix is referenced but not defined in the schema. */
export interface UndefinedPrefix {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "UndefinedPrefix";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** prefix */
  prefix: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** Something unexpected went wrong that during schema loading or validation. Consider filing  a bug report with the schema and the error message: {reason} */
export interface UnexpectedError {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "UnexpectedError";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** reason: Message of the underlying exception. */
  reason: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** A reference in the schema points at an element that is not defined. */
export interface UnknownReference {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "UnknownReference";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** reference value */
  reference_value: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** A reference to the `string` type could not be resolved, which almost always means that `linkml:types` was not imported. */
export interface UnknownStringReference {
  /** details: Longer, human-readable message describing the issue in more detail. */
  details?: string;
  /** issue type: The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled automatically with the class name on serialization, and used to recover the concrete issue type when reading a report back. */
  issue_type: "UnknownStringReference";
  /** location: The location in the schema where the issue was found. */
  location: IssueLocation;
  /** message: Short, human-readable message describing the issue. */
  message?: string;
  /** severity: The severity of the issue. */
  severity: IssueSeverity;
}

/** Issue severity: The severity of an issue found during the validation of a LinkML schema. */
export type IssueSeverity =
  | "FATAL"
  | "ERROR"
  | "WARNING";
