// Generated by LinkML-Scala from https://linkml.neverblink.eu/model/issue-types
// DO NOT EDIT.

package eu.neverblink.linkml.validation

import eu.neverblink.linkml.runtime.*

/** A region of code in a schema where an issue was found. This class is a simplified (special case)
  * version of the `region` object from the SARIF specification:
  * https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790935
  *
  * Indexing is 1-based.
  *
  * @param endColumn
  *   The column number in the schema where the issue ends (1-based, EXCLUSIVE).
  * @param endLine
  *   The line number in the schema where the issue ends (1-based, inclusive).
  * @param startColumn
  *   The column number in the schema where the issue starts (1-based).
  * @param startLine
  *   The line number in the schema where the issue starts (1-based).
  * @see
  *   From schema: https://linkml.neverblink.eu/model/validation-report
  */
final case class CodeRegion(
    @named("end_column")
    endColumn: Option[Int] = None,
    @named("end_line")
    endLine: Option[Int] = None,
    @named("start_column")
    startColumn: Int,
    @named("start_line")
    startLine: Int,
) {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  def infer(): CodeRegion =
    this
}
