// Generated by LinkML-Scala from https://linkml.neverblink.eu/model/issue-types
// DO NOT EDIT.

package eu.neverblink.linkml.validation

import eu.neverblink.linkml.runtime.*

/** A URI or CURIE value in the schema is not a valid URI or `prefix:localname` pair.
  *
  * @param details
  *   Longer, human-readable message describing the issue in more detail.
  * @param issueType
  *   The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled
  *   automatically with the class name on serialization, and used to recover the concrete issue
  *   type when reading a report back.
  * @param location
  *   The location in the schema where the issue was found.
  *
  * @param message
  *   Short, human-readable message describing the issue.
  * @param severity
  *   The severity of the issue.
  *
  * @see
  *   From schema: https://linkml.neverblink.eu/model/issue-types
  */
final case class InvalidUriOrCurie(
    details: Option[String] = None,
    @named("issue_type")
    @serializeDefault
    issueType: String = "InvalidUriOrCurie",
    location: IssueLocation,
    message: Option[String] = None,
    @serializeDefault
    severity: IssueSeverity = IssueSeverity.Error,
    @named("uri_or_curie")
    uriOrCurie: UriOrCurie,
) extends SchemaError {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): InvalidUriOrCurie =
    copy(
      details = inferOptional(
        "details",
        details,
        "Invalid URI or CURIE '" + stringify(uriOrCurie) + "' at " + inferenceInput(
          "location.json_pointer",
          location.jsonPointer,
        ) + ". A valid URI must be a valid IRI, and a valid CURIE must be of the form 'prefix:localname' where 'localname' is a valid relative IRI reference.",
      ),
      message = inferOptional(
        "message",
        message,
        "Invalid URI or CURIE '" + stringify(uriOrCurie) + "' at " + inferenceInput(
          "location.json_pointer",
          location.jsonPointer,
        ),
      ),
    )
}
