// Generated by LinkML-Scala from https://linkml.neverblink.eu/model/issue-types
// DO NOT EDIT.

package eu.neverblink.linkml.validation

import eu.neverblink.linkml.runtime.*

/** A `range` points at an element that cannot be used as a range.
  *
  * @param actualType
  *   The metamodel type the range actually resolved to.
  * @param details
  *   Longer, human-readable message describing the issue in more detail.
  * @param issueType
  *   The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled
  *   automatically with the class name on serialization, and used to recover the concrete issue
  *   type when reading a report back.
  * @param location
  *   The location in the schema where the issue was found.
  *
  * @param message
  *   Short, human-readable message describing the issue.
  * @param severity
  *   The severity of the issue.
  *
  * @see
  *   From schema: https://linkml.neverblink.eu/model/issue-types
  */
final case class InvalidRange(
    @named("actual_type")
    actualType: String,
    details: Option[String] = None,
    @named("issue_type")
    @serializeDefault
    issueType: String = "InvalidRange",
    location: IssueLocation,
    message: Option[String] = None,
    @named("range_value")
    rangeValue: String,
    @serializeDefault
    severity: IssueSeverity = IssueSeverity.Fatal,
) extends SchemaFatal {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): InvalidRange =
    copy(
      details = inferOptional(
        "details",
        details,
        "Invalid range '" + rangeValue + "' at " + inferenceInput(
          "location.json_pointer",
          location.jsonPointer,
        ) + ", which refers to " + actualType + ". Ranges can only reference types, classes or enums.",
      ),
      message = inferOptional(
        "message",
        message,
        "Invalid range '" + rangeValue + "' at " + inferenceInput(
          "location.json_pointer",
          location.jsonPointer,
        ),
      ),
    )
}
