// Generated by LinkML-Scala from https://linkml.neverblink.eu/model/issue-types
// DO NOT EDIT.

package eu.neverblink.linkml.validation

import eu.neverblink.linkml.runtime.*

/** A location in a schema where an issue was found.
  *
  * @param codeRegion
  *   A region of code in the schema where the issue was found.
  * @param jsonPointer
  *   A JSON pointer to the location in the schema where the issue was found.
  * @param schemaId
  *   The identifier of the schema in which the issue was found. Always present, unless the issue
  *   pertains to the lack of the identifier itself.
  * @see
  *   From schema: https://linkml.neverblink.eu/model/validation-report
  */
final case class IssueLocation(
    @named("code_region")
    codeRegion: Option[CodeRegion] = None,
    @named("json_pointer")
    jsonPointer: Option[String] = None,
    @named("schema_id")
    schemaId: Option[Uri] = None,
) {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  def infer(): IssueLocation =
    this
}
