// Generated by LinkML-Scala from https://linkml.neverblink.eu/model/issue-types
// DO NOT EDIT.

package eu.neverblink.linkml.validation

import eu.neverblink.linkml.runtime.*

/** The schema has no `default_range` and no `string` type to fall back on.
  *
  * @param details
  *   Longer, human-readable message describing the issue in more detail.
  * @param issueType
  *   The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled
  *   automatically with the class name on serialization, and used to recover the concrete issue
  *   type when reading a report back.
  * @param location
  *   The location in the schema where the issue was found.
  *
  * @param message
  *   Short, human-readable message describing the issue.
  * @param severity
  *   The severity of the issue.
  *
  * @see
  *   From schema: https://linkml.neverblink.eu/model/issue-types
  */
final case class UndefinedDefaultRange(
    details: Option[String] = None,
    @named("issue_type")
    @serializeDefault
    issueType: String = "UndefinedDefaultRange",
    location: IssueLocation,
    message: Option[String] = None,
    @serializeDefault
    severity: IssueSeverity = IssueSeverity.Warning,
) extends SchemaWarning {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): UndefinedDefaultRange =
    copy(
      details = inferOptional(
        "details",
        details,
        "The 'default_range' of the schema is not defined and could not find a 'string' type to use as a fallback. This will become a fatal error if any slots in the schema omit their 'range'. Add a 'default_range' to the schema, import 'linkml:types', or define a 'string' type to fix.",
      ),
      message = inferOptional("message", message, "No 'default_range' is defined in the schema"),
    )
}
