// Generated by LinkML-Scala from https://linkml.neverblink.eu/model/issue-types
// DO NOT EDIT.

package eu.neverblink.linkml.validation

import eu.neverblink.linkml.runtime.*

/** Something unexpected went wrong that during schema loading or validation. Consider filing a bug
  * report with the schema and the error message: {reason}
  *
  * @param details
  *   Longer, human-readable message describing the issue in more detail.
  * @param issueType
  *   The type of the issue: name of the concrete issue class (e.g. `InvalidRange`). Filled
  *   automatically with the class name on serialization, and used to recover the concrete issue
  *   type when reading a report back.
  * @param location
  *   The location in the schema where the issue was found.
  *
  * @param message
  *   Short, human-readable message describing the issue.
  * @param reason
  *   Message of the underlying exception.
  * @param severity
  *   The severity of the issue.
  *
  * @see
  *   From schema: https://linkml.neverblink.eu/model/issue-types
  */
final case class UnexpectedError(
    details: Option[String] = None,
    @named("issue_type")
    @serializeDefault
    issueType: String = "UnexpectedError",
    location: IssueLocation,
    message: Option[String] = None,
    reason: String,
    @serializeDefault
    severity: IssueSeverity = IssueSeverity.Fatal,
) extends SchemaFatal {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): UnexpectedError =
    copy(
      message =
        inferOptional("message", message, "Unexpected error while loading the schema: " + reason),
    )
}
