package eu.neverblink.linkml.rdf

abstract class Vocabulary(val prefix: String) {
  def get(suffix: String): Iri = new Iri(prefix.concat(suffix))
}

object XmlSchema extends Vocabulary("http://www.w3.org/2001/XMLSchema#") {
  val string: Iri = get("string")
  val integer: Iri = get("integer")
  val boolean: Iri = get("boolean")
  val decimal: Iri = get("decimal")
  val double: Iri = get("double")
  val float: Iri = get("float")
  val date: Iri = get("date")
  val dateTime: Iri = get("dateTime")
  val time: Iri = get("time")
  val anyURI: Iri = get("anyURI")
  val minInclusive: Iri = get("minInclusive")
  val maxInclusive: Iri = get("maxInclusive")
  val minExclusive: Iri = get("minExclusive")
  val maxExclusive: Iri = get("maxExclusive")
  val pattern: Iri = get("pattern")
  val nonNegativeInteger: Iri = get("nonNegativeInteger")
}

object Rdf extends Vocabulary("http://www.w3.org/1999/02/22-rdf-syntax-ns#") {
  val Property: Iri = get("Property")
  val first: Iri = get("first")
  val nil: Iri = get("nil")
  val langString: Iri = get("langString")
  val rest: Iri = get("rest")
  val `type`: Iri = get("type")
}

object Shacl extends Vocabulary("http://www.w3.org/ns/shacl#") {
  val BlankNodeOrIRI: Iri = get("BlankNodeOrIRI")
  val IRI: Iri = get("IRI")
  val Literal: Iri = get("Literal")
  val NodeShape: Iri = get("NodeShape")
  val PropertyGroup: Iri = get("PropertyGroup")
  val PropertyShape: Iri = get("PropertyShape")
  val `class`: Iri = get("class")
  val closed: Iri = get("closed")
  val datatype: Iri = get("datatype")
  val description: Iri = get("description")
  val group: Iri = get("group")
  val ignoredProperties: Iri = get("ignoredProperties")
  val in: Iri = get("in")
  val maxCount: Iri = get("maxCount")
  val maxInclusive: Iri = get("maxInclusive")
  val minCount: Iri = get("minCount")
  val minInclusive: Iri = get("minInclusive")
  val name: Iri = get("name")
  val nodeKind: Iri = get("nodeKind")
  val or: Iri = get("or")
  val order: Iri = get("order")
  val declare: Iri = get("declare")
  val namespace: Iri = get("namespace")
  val path: Iri = get("path")
  val pattern: Iri = get("pattern")
  val property: Iri = get("property")
  val targetClass: Iri = get("targetClass")
}

object Rdfs extends Vocabulary("http://www.w3.org/2000/01/rdf-schema#") {
  val Class: Iri = get("Class")
  val Datatype: Iri = get("Datatype")
  val Literal: Iri = get("Literal")
  val Resource: Iri = get("Resource")
  val comment: Iri = get("comment")
  val domain: Iri = get("domain")
  val isDefinedBy: Iri = get("isDefinedBy")
  val label: Iri = get("label")
  val range: Iri = get("range")
  val seeAlso: Iri = get("seeAlso")
  val subClassOf: Iri = get("subClassOf")
  val subPropertyOf: Iri = get("subPropertyOf")
}

object Skos extends Vocabulary("http://www.w3.org/2004/02/skos/core#") {
  val definition: Iri = get("definition")
}

object Owl extends Vocabulary("http://www.w3.org/2002/07/owl#") {
  val AllDifferent: Iri = get("AllDifferent")
  val AllDisjointClasses: Iri = get("AllDisjointClasses")
  val AllDisjointProperties: Iri = get("AllDisjointProperties")
  val AnnotationProperty: Iri = get("AnnotationProperty")
  val AsymmetricProperty: Iri = get("AsymmetricProperty")
  val Axiom: Iri = get("Axiom")
  val Class: Iri = get("Class")
  val DatatypeProperty: Iri = get("DatatypeProperty")
  val DeprecatedClass: Iri = get("DeprecatedClass")
  val DeprecatedProperty: Iri = get("DeprecatedProperty")
  val FunctionalProperty: Iri = get("FunctionalProperty")
  val InverseFunctionalProperty: Iri = get("InverseFunctionalProperty")
  val IrreflexiveProperty: Iri = get("IrreflexiveProperty")
  val NamedIndividual: Iri = get("NamedIndividual")
  val Nothing: Iri = get("Nothing")
  val ObjectProperty: Iri = get("ObjectProperty")
  val Ontology: Iri = get("Ontology")
  val ReflexiveProperty: Iri = get("ReflexiveProperty")
  val Restriction: Iri = get("Restriction")
  val SymmetricProperty: Iri = get("SymmetricProperty")
  val Thing: Iri = get("Thing")
  val TransitiveProperty: Iri = get("TransitiveProperty")
  val allValuesFrom: Iri = get("allValuesFrom")
  val annotatedProperty: Iri = get("annotatedProperty")
  val annotatedSource: Iri = get("annotatedSource")
  val annotatedTarget: Iri = get("annotatedTarget")
  val cardinality: Iri = get("cardinality")
  val complementOf: Iri = get("complementOf")
  val datatypeComplementOf: Iri = get("datatypeComplementOf")
  val deprecated: Iri = get("deprecated")
  val differentFrom: Iri = get("differentFrom")
  val disjointUnionOf: Iri = get("disjointUnionOf")
  val disjointWith: Iri = get("disjointWith")
  val distinctMembers: Iri = get("distinctMembers")
  val equivalentClass: Iri = get("equivalentClass")
  val equivalentProperty: Iri = get("equivalentProperty")
  val hasKey: Iri = get("hasKey")
  val hasSelf: Iri = get("hasSelf")
  val hasValue: Iri = get("hasValue")
  val imports: Iri = get("imports")
  val intersectionOf: Iri = get("intersectionOf")
  val inverseOf: Iri = get("inverseOf")
  val maxCardinality: Iri = get("maxCardinality")
  val maxQualifiedCardinality: Iri = get("maxQualifiedCardinality")
  val members: Iri = get("members")
  val minCardinality: Iri = get("minCardinality")
  val minQualifiedCardinality: Iri = get("minQualifiedCardinality")
  val onClass: Iri = get("onClass")
  val onDataRange: Iri = get("onDataRange")
  val onDatatype: Iri = get("onDatatype")
  val onProperty: Iri = get("onProperty")
  val oneOf: Iri = get("oneOf")
  val priorVersion: Iri = get("priorVersion")
  val propertyChainAxiom: Iri = get("propertyChainAxiom")
  val propertyDisjointWith: Iri = get("propertyDisjointWith")
  val qualifiedCardinality: Iri = get("qualifiedCardinality")
  val sameAs: Iri = get("sameAs")
  val someValuesFrom: Iri = get("someValuesFrom")
  val unionOf: Iri = get("unionOf")
  val versionIRI: Iri = get("versionIRI")
  val versionInfo: Iri = get("versionInfo")
  val withRestrictions: Iri = get("withRestrictions")
}
