#!/usr/bin/env python3
"""Regenerate the derived parts of the `linkml` agent skill.

Files with a GENERATED banner in `.agents/skills/linkml/` come from here, so the skill
cannot drift from the implementation it describes. Sources:

  out/metamodel/definitions.dest/*.yaml  the real LinkML metamodel (fetched by the build)
  docs/implementation_differences.md     what linkml-scala does not support
  tests/resources/models/                the known-good example schemas

The metamodel YAML is not committed. Fetch it first:

    ./mill show metamodel.definitions

Deliberately *not* generated: a CLI reference, or a catalogue of validator issues. The CLI's
`--help` and its validation messages are self-describing, so a bundled copy would only rot.

Usage:
    python3 .agents/generate.py            # write the files
    python3 .agents/generate.py --check    # fail if they are stale
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
SKILL = REPO / ".agents" / "skills" / "linkml"
METAMODEL = REPO / "out" / "metamodel" / "definitions.dest"

BANNER = (
    "<!-- GENERATED by .agents/generate.py - do not edit by hand. -->\n"
    "<!-- Regenerate with: python3 .agents/generate.py -->\n"
)

# The metamodel ships several schemas. Only some describe the vocabulary you use when
# authoring: datasets.yaml is a separate data-package model, array.yaml covers arrays
# (unsupported here), and validation.yaml is the validation-report model. Excluding them
# keeps the lookup table to what an author can actually write.
AUTHORING_SCHEMAS = ("meta.yaml", "types.yaml", "mappings.yaml", "extensions.yaml",
                     "annotations.yaml", "units.yaml")

TIERS = {
    "MinimalSubset": "min",
    "BasicSubset": "basic",
    "SpecificationSubset": "spec",
    "ObjectOrientedProfile": "oo",
    "RelationalModelProfile": "rel",
}


def one_line(text: object, limit: int = 90) -> str:
    if not text:
        return ""
    flat = " ".join(str(text).split())
    if len(flat) > limit:
        flat = flat[: limit - 1].rstrip() + "…"
    return flat.replace("\t", " ")


def load_metamodel() -> dict:
    if not (METAMODEL / "meta.yaml").is_file():
        sys.exit(
            f"Metamodel YAML not found under {METAMODEL.relative_to(REPO)}.\n"
            "Fetch it first with:  ./mill show metamodel.definitions"
        )
    merged: dict = {"classes": {}, "slots": {}, "enums": {}, "types": {}}
    for name in AUTHORING_SCHEMAS:
        doc = yaml.safe_load((METAMODEL / name).read_text()) or {}
        for section in merged:
            merged[section].update(doc.get(section) or {})
    return merged


def gen_metaslots(meta: dict) -> str:
    """A compact, greppable index of the authoring vocabulary.

    TSV rather than Markdown on purpose: this is queried with grep/awk, never read from
    start to finish, and pipe-aligned tables would cost tokens for nothing.
    """
    classes, slots = meta["classes"], meta["slots"]

    owners: dict[str, list[str]] = {}
    for cname, cdef in classes.items():
        for sname in (cdef or {}).get("slots") or []:
            owners.setdefault(sname, []).append(cname)

    rows = []
    for name, sdef in sorted(slots.items()):
        sdef = sdef or {}
        used = owners.get(name) or ([sdef["domain"]] if sdef.get("domain") else [])
        if len(used) > 3:
            used = used[:3] + [f"+{len(owners[name]) - 3}"]
        card = "multi" if sdef.get("multivalued") else "single"
        if sdef.get("required"):
            card += ",required"
        tiers = [TIERS[s] for s in sdef.get("in_subset") or [] if s in TIERS]
        rows.append(
            "\t".join([name, ",".join(used) or "-", str(sdef.get("range") or "string"),
                       card, ",".join(tiers) or "-", one_line(sdef.get("description"))])
        )

    header = textwrap.dedent(
        f"""\
        # GENERATED by .agents/generate.py - do not edit by hand.
        #
        # The LinkML authoring vocabulary: every metamodel slot you may write in a schema,
        # {len(rows)} of them. Query it, do not read it. Columns are tab-separated, so anchor
        # on the column - a bare `grep basic` also matches every description with that word.
        #
        #   grep -P '^inlined\\t' 900-metaslots.tsv                              # one slot
        #   awk -F'\\t' '$5 ~ /min|basic/ {{print $1}}' 900-metaslots.tsv          # everyday slots
        #   awk -F'\\t' '$2 ~ /class_definition/ {{print $1}}' 900-metaslots.tsv  # what a class carries
        #
        # tier: min/basic = commonly used, spec = in the formal specification,
        # oo/rel = object-oriented / relational profiles only.
        #
        # used_on lists only classes declaring a slot directly. Classes also inherit every
        # slot of their is_a/mixins ancestors, so class_definition does accept name and
        # description even though those are declared on element.
        #
        # Presence here means the *metamodel* defines it, NOT that linkml-scala implements
        # it. Check 200-limitations.md before relying on anything unusual.
        #
        # slot\tused_on\trange\tcardinality\ttier\tdescription
        """
    )
    return header + "\n".join(rows) + "\n"


def gen_limitations() -> str:
    body = (REPO / "docs" / "implementation_differences.md").read_text()
    return (
        BANNER
        + "<!-- Source: docs/implementation_differences.md -->\n\n"
        "> **Read this before using any LinkML feature you have not used with linkml-scala\n"
        "> before.** Everything under *Limitations* is ignored or rejected. The semantics\n"
        "> sections diverge from linkml-python, so a schema can behave differently here.\n\n"
        + body
    )


def gen_examples() -> str:
    root = REPO / "tests" / "resources" / "models"
    rows = []
    for model in sorted(root.rglob("model.yaml")):
        rel = model.parent.relative_to(root)
        try:
            doc = yaml.safe_load(model.read_text()) or {}
        except yaml.YAMLError:
            continue
        # Only a real description earns a note. The class names in these test models are
        # placeholders (`SomeClass`, `SomeOtherClass`), so listing them told the reader
        # nothing the feature column had not already said.
        note = one_line(doc.get("description"), 60)
        counts = []
        for kind in ("valid", "invalid"):
            d = model.parent / kind
            counts.append(len(list(d.rglob("*"))) if d.is_dir() else 0)
        rows.append(f"| `{rel}` | {counts[0]} | {counts[1]} | {note} |")

    return "\n".join([
        BANNER,
        "# Known-good example schemas\n",
        "Dozens of schemas from the linkml-scala test suite. Each exercises one feature and is",
        "verified against every generator on every commit, so when you are unsure how something is",
        "written, read the matching `model.yaml` instead of guessing.\n",
        "Paths are relative to `tests/resources/models/`:",
        "<https://github.com/NeverBlink-OSS/linkml-scala/tree/main/tests/resources/models>\n",
        "`valid`/`invalid` count the instance-data files shipped with the schema — worked examples",
        "of what it does and does not accept, and the fastest way to sanity-check a data validator.\n",
        "| feature | valid | invalid | notes |",
        "|---|---|---|---|",
        *rows,
    ]) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if any file is stale")
    args = ap.parse_args()

    meta = load_metamodel()
    outputs = {
        "900-metaslots.tsv": gen_metaslots(meta),
        "200-limitations.md": gen_limitations(),
        "910-examples.md": gen_examples(),
    }

    stale = []
    for name, content in outputs.items():
        target = SKILL / name
        if target.is_file() and target.read_text() == content:
            continue
        if args.check:
            stale.append(name)
        else:
            target.write_text(content)
            print(f"wrote {target.relative_to(REPO)} ({len(content):,} bytes)")

    if stale:
        print(
            "\nGenerated skill files are out of date:\n  " + "\n  ".join(stale)
            + "\n\nRegenerate with:  python3 .agents/generate.py",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print("generated skill files are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
