package eu.neverblink.linkml.generator.util

import eu.neverblink.linkml.schemaview.SchemaView

/** The comment at the top of every generated code file. */
object GeneratedHeader {

  /** The header as line comments starting with [[commentPrefix]], ending with a newline. */
  def apply(commentPrefix: String)(using sv: SchemaView): String = {
    val id = sv.root.id.uri(using sv.rootPrefixResolver)
    s"$commentPrefix Generated by LinkML-Scala from $id\n$commentPrefix DO NOT EDIT.\n"
  }
}
