package eu.neverblink.linkml.generator.util

import eu.neverblink.linkml.schemaview.SchemaView

/** The comment at the top of every generated code file. */
object GeneratedHeader {
  private val lead = " Generated by LinkML-Scala from "

  /** The header as line comments starting with [[commentPrefix]], ending with a newline. */
  def apply(commentPrefix: String)(using sv: SchemaView): String = {
    val id = sv.root.id.uri(using sv.rootPrefixResolver)
    s"$commentPrefix$lead$id\n$commentPrefix DO NOT EDIT.\n"
  }

  /** Whether [[line]] is the first line of a header written with [[commentPrefix]]. */
  def startsHeader(line: String, commentPrefix: String): Boolean =
    line.startsWith(commentPrefix) && line.startsWith(lead, commentPrefix.length)
}
