// Generated by LinkML-Scala from https://w3id.org/linkml/meta
// DO NOT EDIT.

package eu.neverblink.linkml.metamodel

import eu.neverblink.linkml.runtime.*

/** A tag/value pair with the semantics of OWL Annotation
  *
  * @param annotations
  *   A collection of tag/text tuples with the semantics of OWL Annotation
  * @param extensionTag
  *   A tag associated with an extension
  * @param extensionValue
  *   The actual annotation
  * @param extensions
  *   A tag/text tuple attached to an arbitrary element
  * @see
  *   From schema: https://w3id.org/linkml/annotations
  */
final case class Annotation(
    @simpleDict
    annotations: Map[String, Annotation] = Map(),
    @id
    @named("tag")
    extensionTag: UriOrCurie,
    @value
    @named("value")
    extensionValue: LinkmlAny,
    @simpleDict
    extensions: Map[String, ExtensionImpl] = Map(),
) extends Extension,
      Annotatable {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): Annotation =
    this
}
