// Generated by LinkML-Scala from https://w3id.org/linkml/meta
// DO NOT EDIT.

package eu.neverblink.linkml.metamodel

import eu.neverblink.linkml.runtime.*

/** A type expression that is not a top-level named type definition. Used for nesting.
  *
  * @param pattern
  *   The string value of the slot must conform to this regular expression expressed in the string
  * @param anyOf
  *   Holds if at least one of the expressions hold
  * @param exactlyOneOf
  *   Holds if only one of the expressions hold
  * @param noneOf
  *   Holds if none of the expressions hold
  * @param allOf
  *   Holds if all of the expressions hold
  * @param equalsNumber
  *   The slot must have range of a number and the value of the slot must equal the specified value
  * @param equalsString
  *   The slot must have range string and the value of the slot must equal the specified value
  * @param equalsStringIn
  *   The slot must have range string and the value of the slot must equal one of the specified
  *   values
  * @param implicitPrefix
  *   Causes the slot value to be interpreted as a uriorcurie after prefixing with this string
  * @param maximumValue
  *   For ordinal ranges, the value must be equal to or lower than this
  * @param minimumValue
  *   For ordinal ranges, the value must be equal to or higher than this
  * @param structuredPattern
  *   The string value of the slot must conform to the regular expression in the pattern expression
  * @param unit
  *   An encoding of a unit
  * @see
  *   From schema: https://w3id.org/linkml/meta
  */
final case class AnonymousTypeExpression(
    pattern: Option[String] = None,
    @named("any_of")
    anyOf: Seq[AnonymousTypeExpression] = Seq(),
    @named("exactly_one_of")
    exactlyOneOf: Seq[AnonymousTypeExpression] = Seq(),
    @named("none_of")
    noneOf: Seq[AnonymousTypeExpression] = Seq(),
    @named("all_of")
    allOf: Seq[AnonymousTypeExpression] = Seq(),
    @named("equals_number")
    equalsNumber: Option[Int] = None,
    @named("equals_string")
    equalsString: Option[String] = None,
    @named("equals_string_in")
    equalsStringIn: Seq[String] = Seq(),
    @named("implicit_prefix")
    implicitPrefix: Option[String] = None,
    @named("maximum_value")
    maximumValue: Option[LinkmlAny] = None,
    @named("minimum_value")
    minimumValue: Option[LinkmlAny] = None,
    @named("structured_pattern")
    structuredPattern: Option[PatternExpression] = None,
    unit: Option[UnitOfMeasure] = None,
) extends TypeExpression {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): AnonymousTypeExpression =
    this
}
