// Generated by LinkML-Scala from https://w3id.org/linkml/meta
// DO NOT EDIT.

package eu.neverblink.linkml.metamodel

import eu.neverblink.linkml.runtime.*

/** Defines the dimensions of an array
  *
  * @param title
  *   A concise human-readable display label for the element. The title should mirror the name, and
  *   should use ordinary textual punctuation.
  * @param description
  *   A textual description of the element's purpose and use
  * @param rank
  *   The relative order in which the element occurs, lower values are given precedence
  * @param aliases
  *   Alternate names/labels for the element. These do not alter the semantics of the schema, but
  *   may be useful to support search and alignment.
  * @param altDescriptions
  *   A sourced alternative description for an element
  * @param annotations
  *   A collection of tag/text tuples with the semantics of OWL Annotation
  * @param broadMappings
  *   A list of terms from different schemas or terminology systems that have broader meaning.
  * @param categories
  *   Controlled terms used to categorize an element.
  * @param closeMappings
  *   A list of terms from different schemas or terminology systems that have close meaning.
  * @param comments
  *   Notes and comments about an element intended primarily for external consumption
  * @param contributors
  *   Agent that contributed to the element
  * @param createdBy
  *   Agent that created the element
  * @param createdOn
  *   Time at which the element was created
  * @param deprecated
  *   Description of why and when this element will no longer be used
  * @param deprecatedElementHasExactReplacement
  *   When an element is deprecated, it can be automatically replaced by this uri or curie
  * @param deprecatedElementHasPossibleReplacement
  *   When an element is deprecated, it can be potentially replaced by this uri or curie
  * @param dimensions
  *   Definitions of each axis in the array
  * @param exactMappings
  *   A list of terms from different schemas or terminology systems that have identical meaning.
  * @param exactNumberDimensions
  *   Exact number of dimensions in the array
  * @param examples
  *   Example usages of an element
  * @param extensions
  *   A tag/text tuple attached to an arbitrary element
  * @param fromSchema
  *   Id of the schema that defined the element
  * @param importedFrom
  *   The imports entry that this element was derived from. Empty means primary source
  * @param inLanguage
  *   The primary language used in the sources
  * @param inSubset
  *   Used to indicate membership of a term in a defined subset of terms used for a particular
  *   domain or application.
  * @param keywords
  *   Keywords or tags used to describe the element
  * @param lastUpdatedOn
  *   Time at which the element was last updated
  * @param mappings
  *   A list of terms from different schemas or terminology systems that have comparable meaning.
  *   These may include terms that are precisely equivalent, broader or narrower in meaning, or
  *   otherwise semantically related but not equivalent from a strict ontological perspective.
  * @param maximumNumberDimensions
  *   Maximum number of dimensions in the array, or False if explicitly no maximum. If this is
  *   unset, and an explicit list of dimensions are passed using dimensions, then this is
  *   interpreted as a closed list and the maximum_number_dimensions is the length of the dimensions
  *   list, unless this value is set to False
  * @param minimumNumberDimensions
  *   Minimum number of dimensions in the array
  * @param modifiedBy
  *   Agent that modified the element
  * @param narrowMappings
  *   A list of terms from different schemas or terminology systems that have narrower meaning.
  * @param notes
  *   Editorial notes about an element intended primarily for internal consumption
  * @param relatedMappings
  *   A list of terms from different schemas or terminology systems that have related meaning.
  * @param seeAlso
  *   A list of related entities or URLs that may be of relevance
  * @param source
  *   A related resource from which the element is derived.
  * @param status
  *   Status of the element
  * @param structuredAliases
  *   A list of structured_alias objects, used to provide aliases in conjunction with additional
  *   metadata.
  * @param todos
  *   Outstanding issues that needs resolution
  * @see
  *   From schema: https://w3id.org/linkml/meta
  */
final case class ArrayExpression(
    title: Option[LocalizedText] = None,
    description: Option[LocalizedText] = None,
    rank: Option[Int] = None,
    aliases: Seq[LocalizedText] = Seq(),
    @named("alt_descriptions")
    @simpleDict
    altDescriptions: Map[String, AltDescription] = Map(),
    @simpleDict
    annotations: Map[String, Annotation] = Map(),
    @named("broad_mappings")
    broadMappings: Seq[UriOrCurie] = Seq(),
    categories: Seq[UriOrCurie] = Seq(),
    @named("close_mappings")
    closeMappings: Seq[UriOrCurie] = Seq(),
    comments: Seq[LocalizedText] = Seq(),
    contributors: Seq[UriOrCurie] = Seq(),
    @named("created_by")
    createdBy: Option[UriOrCurie] = None,
    @named("created_on")
    createdOn: Option[LinkmlDateTime] = None,
    deprecated: Option[LocalizedText] = None,
    @named("deprecated_element_has_exact_replacement")
    deprecatedElementHasExactReplacement: Option[UriOrCurie] = None,
    @named("deprecated_element_has_possible_replacement")
    deprecatedElementHasPossibleReplacement: Option[UriOrCurie] = None,
    dimensions: Seq[DimensionExpression] = Seq(),
    @named("exact_mappings")
    exactMappings: Seq[UriOrCurie] = Seq(),
    @named("exact_number_dimensions")
    exactNumberDimensions: Option[Int] = None,
    examples: Seq[Example] = Seq(),
    @simpleDict
    extensions: Map[String, ExtensionImpl] = Map(),
    @named("from_schema")
    fromSchema: Option[Uri] = None,
    @named("imported_from")
    importedFrom: Option[String] = None,
    @named("in_language")
    inLanguage: Option[String] = None,
    @named("in_subset")
    inSubset: Seq[Reference[SubsetDefinition]] = Seq(),
    keywords: Seq[LocalizedText] = Seq(),
    @named("last_updated_on")
    lastUpdatedOn: Option[LinkmlDateTime] = None,
    mappings: Seq[UriOrCurie] = Seq(),
    @named("maximum_number_dimensions")
    maximumNumberDimensions: Option[LinkmlAny] = None,
    @named("minimum_number_dimensions")
    minimumNumberDimensions: Option[Int] = None,
    @named("modified_by")
    modifiedBy: Option[UriOrCurie] = None,
    @named("narrow_mappings")
    narrowMappings: Seq[UriOrCurie] = Seq(),
    notes: Seq[LocalizedText] = Seq(),
    @named("related_mappings")
    relatedMappings: Seq[UriOrCurie] = Seq(),
    @named("see_also")
    seeAlso: Seq[UriOrCurie] = Seq(),
    source: Option[UriOrCurie] = None,
    status: Option[UriOrCurie] = None,
    @named("structured_aliases")
    structuredAliases: Seq[StructuredAlias] = Seq(),
    todos: Seq[String] = Seq(),
) extends Extensible,
      Annotatable,
      CommonMetadata {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): ArrayExpression =
    this
}
