// Generated by LinkML-Scala from https://w3id.org/linkml/meta
// DO NOT EDIT.

package eu.neverblink.linkml.metamodel

import eu.neverblink.linkml.runtime.*

/** Usage example and description
  *
  * @param value
  *   Example value
  * @param valueDescription
  *   Description of what the value is doing
  * @param valueObject
  *   Direct object representation of the example
  * @see
  *   From schema: https://w3id.org/linkml/meta
  */
final case class Example(
    value: Option[String] = None,
    @named("description")
    valueDescription: Option[LocalizedText] = None,
    @named("object")
    valueObject: Option[LinkmlAny] = None,
) {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  def infer(): Example =
    this
}
