// Generated by LinkML-Scala from https://w3id.org/linkml/meta
// DO NOT EDIT.

package eu.neverblink.linkml.metamodel

import eu.neverblink.linkml.runtime.*

/** An expression that defines how to handle additional data in an instance of class beyond the
  * slots/attributes defined for that class. See `extra_slots` for usage examples.
  *
  * @param allowed
  *   Whether or not something is allowed. Usage defined by context.
  * @param rangeExpression
  *   A range that is described as a boolean expression combining existing ranges
  * @see
  *   From schema: https://w3id.org/linkml/meta
  */
final case class ExtraSlotsExpression(
    allowed: Option[Boolean] = None,
    @named("range_expression")
    rangeExpression: Option[AnonymousSlotExpression] = None,
) extends Expression {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): ExtraSlotsExpression =
    this
}
