// Generated by LinkML-Scala from https://w3id.org/linkml/meta
// DO NOT EDIT.

package eu.neverblink.linkml.metamodel

import eu.neverblink.linkml.runtime.*

/** An attributed label
  *
  * @param localNameSource
  *   The ncname of the source of the name
  * @param localNameValue
  *   A name assigned to an element in a given ontology
  * @see
  *   From schema: https://w3id.org/linkml/meta
  */
final case class LocalName(
    @id
    @named("local_name_source")
    localNameSource: NcName,
    @value
    @named("local_name_value")
    localNameValue: LocalizedText,
) {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  def infer(): LocalName =
    this
}
