// Generated by LinkML-Scala from https://w3id.org/linkml/meta
// DO NOT EDIT.

package eu.neverblink.linkml.metamodel

import eu.neverblink.linkml.runtime.*

/** Prefix URI tuple
  *
  * @param prefixPrefix
  *   The prefix components of a prefix expansions. This is the part that appears before the colon
  *   in a CURIE.
  * @param prefixReference
  *   The namespace to which a prefix expands to.
  * @see
  *   From schema: https://w3id.org/linkml/meta
  */
final case class Prefix(
    @id
    @named("prefix_prefix")
    prefixPrefix: NcName,
    @value
    @named("prefix_reference")
    prefixReference: Uri,
) {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  def infer(): Prefix =
    this
}
