// Generated by LinkML-Scala from https://w3id.org/linkml/meta
// DO NOT EDIT.

package eu.neverblink.linkml.metamodel

import eu.neverblink.linkml.runtime.*

/** A query that is used on an enum expression to dynamically obtain a set of permissible values via
  * walking from a set of source nodes to a set of descendants or ancestors over a set of
  * relationship types.
  *
  * @param includeSelf
  *   True if the query is reflexive
  * @param isDirect
  *   True if the reachability query should only include directly related nodes, if False then
  *   include also transitively connected
  * @param relationshipTypes
  *   A list of relationship types (properties) that are used in a reachability query
  * @param sourceNodes
  *   A list of nodes that are used in the reachability query
  * @param sourceOntology
  *   An ontology or vocabulary or terminology that is used in a query to obtain a set of
  *   permissible values
  * @param traverseUp
  *   True if the direction of the reachability query is reversed and ancestors are retrieved
  * @see
  *   From schema: https://w3id.org/linkml/meta
  */
final case class ReachabilityQuery(
    @named("include_self")
    includeSelf: Boolean = false,
    @named("is_direct")
    isDirect: Boolean = false,
    @named("relationship_types")
    relationshipTypes: Seq[UriOrCurie] = Seq(),
    @named("source_nodes")
    sourceNodes: Seq[UriOrCurie] = Seq(),
    @named("source_ontology")
    sourceOntology: Option[UriOrCurie] = None,
    @named("traverse_up")
    traverseUp: Boolean = false,
) {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  def infer(): ReachabilityQuery =
    this
}
