// Generated by LinkML-Scala from https://w3id.org/linkml/meta
// DO NOT EDIT.

package eu.neverblink.linkml.metamodel

import eu.neverblink.linkml.runtime.*

/** A collection of definitions that make up a schema or a data model.
  *
  * @param id
  *   The official schema URI
  * @param name
  *   A unique name for the schema that is both human-readable and consists of only characters from
  *   the NCName set
  * @param classes
  *   An index to the collection of all class definitions in the schema
  * @param title
  *   A concise human-readable display label for the element. The title should mirror the name, and
  *   should use ordinary textual punctuation.
  * @param slotDefinitions
  *   An index to the collection of all slot definitions in the schema
  * @param description
  *   A textual description of the element's purpose and use
  * @param enums
  *   An index to the collection of all enum definitions in the schema
  * @param types
  *   An index to the collection of all type definitions in the schema
  * @param subsets
  *   An index to the collection of all subset definitions in the schema
  * @param prefixes
  *   A collection of prefix expansions that specify how CURIEs can be expanded to URIs
  * @param defaultPrefix
  *   The prefix that is used for all elements within a schema
  * @param defaultRange
  *   Default slot range to be used if range element is omitted from a slot definition
  * @param settings
  *   A collection of global variable settings
  * @param imports
  *   A list of schemas that are to be included in this schema
  * @param license
  *   License for the schema
  * @param rank
  *   The relative order in which the element occurs, lower values are given precedence
  * @param aliases
  *   Alternate names/labels for the element. These do not alter the semantics of the schema, but
  *   may be useful to support search and alignment.
  * @param altDescriptions
  *   A sourced alternative description for an element
  * @param annotations
  *   A collection of tag/text tuples with the semantics of OWL Annotation
  * @param bindings
  *   A collection of enum bindings that specify how a slot can be bound to a permissible value from
  *   an enumeration. LinkML provides enums to allow string values to be restricted to one of a set
  *   of permissible values (specified statically or dynamically). Enum bindings allow enums to be
  *   bound to any object, including complex nested objects. For example, given a (generic) class
  *   Concept with slots id and label, it may be desirable to restrict the values the id takes on in
  *   a given context. For example, a HumanSample class may have a slot for representing sample
  *   site, with a range of concept, but the values of that slot may be restricted to concepts from
  *   a particular branch of an anatomy ontology.
  * @param broadMappings
  *   A list of terms from different schemas or terminology systems that have broader meaning.
  * @param categories
  *   Controlled terms used to categorize an element.
  * @param closeMappings
  *   A list of terms from different schemas or terminology systems that have close meaning.
  * @param comments
  *   Notes and comments about an element intended primarily for external consumption
  * @param conformsTo
  *   An established standard to which the element conforms.
  * @param contributors
  *   Agent that contributed to the element
  * @param createdBy
  *   Agent that created the element
  * @param createdOn
  *   Time at which the element was created
  * @param defaultCuriMaps
  *   Ordered list of prefixcommon biocontexts to be fetched to resolve id prefixes and inline
  *   prefix variables
  * @param definitionUri
  *   The native URI of the element. This is always within the namespace of the containing schema.
  *   Contrast with the assigned URI, via class_uri or slot_uri
  * @param deprecated
  *   Description of why and when this element will no longer be used
  * @param deprecatedElementHasExactReplacement
  *   When an element is deprecated, it can be automatically replaced by this uri or curie
  * @param deprecatedElementHasPossibleReplacement
  *   When an element is deprecated, it can be potentially replaced by this uri or curie
  * @param emitPrefixes
  *   A list of Curie prefixes that are used in the representation of instances of the model. All
  *   prefixes in this list are added to the prefix sections of the target models.
  * @param exactMappings
  *   A list of terms from different schemas or terminology systems that have identical meaning.
  * @param examples
  *   Example usages of an element
  * @param extensions
  *   A tag/text tuple attached to an arbitrary element
  * @param fromSchema
  *   Id of the schema that defined the element
  * @param generationDate
  *   Date and time that the schema was loaded/generated
  * @param idPrefixes
  *   An allowed list of prefixes for which identifiers must conform. The identifier of this class
  *   or slot must begin with the URIs referenced by this prefix
  * @param idPrefixesAreClosed
  *   If true, then the id_prefixes slot is treated as being closed, and any use of an id that does
  *   not have this prefix is considered a violation.
  * @param implements
  *   An element in another schema which this element conforms to. The referenced element is not
  *   imported into the schema for the implementing element. However, the referenced schema may be
  *   used to check conformance of the implementing element.
  * @param importedFrom
  *   The imports entry that this element was derived from. Empty means primary source
  * @param inLanguage
  *   The primary language used in the sources
  * @param inSubset
  *   Used to indicate membership of a term in a defined subset of terms used for a particular
  *   domain or application.
  * @param instantiates
  *   An element in another schema which this element instantiates.
  * @param keywords
  *   Keywords or tags used to describe the element
  * @param lastUpdatedOn
  *   Time at which the element was last updated
  * @param mappings
  *   A list of terms from different schemas or terminology systems that have comparable meaning.
  *   These may include terms that are precisely equivalent, broader or narrower in meaning, or
  *   otherwise semantically related but not equivalent from a strict ontological perspective.
  * @param metamodelVersion
  *   Version of the metamodel used to load the schema
  * @param modifiedBy
  *   Agent that modified the element
  * @param narrowMappings
  *   A list of terms from different schemas or terminology systems that have narrower meaning.
  * @param notes
  *   Editorial notes about an element intended primarily for internal consumption
  * @param relatedMappings
  *   A list of terms from different schemas or terminology systems that have related meaning.
  * @param seeAlso
  *   A list of related entities or URLs that may be of relevance
  * @param slotNamesUnique
  *   If true then induced/mangled slot names are not created for class_usage and attributes
  * @param source
  *   A related resource from which the element is derived.
  * @param sourceFile
  *   Name, uri or description of the source of the schema
  * @param sourceFileDate
  *   Modification date of the source of the schema
  * @param sourceFileSize
  *   Size in bytes of the source of the schema
  * @param status
  *   Status of the element
  * @param structuredAliases
  *   A list of structured_alias objects, used to provide aliases in conjunction with additional
  *   metadata.
  * @param todos
  *   Outstanding issues that needs resolution
  * @param version
  *   Particular version of schema
  * @see
  *   https://en.wikipedia.org/wiki/Data_dictionary
  * @see
  *   Aliases: data dictionary, data model, information model, logical model, schema, model
  * @see
  *   From schema: https://w3id.org/linkml/meta
  */
final case class SchemaDefinition(
    @value
    id: Uri,
    @id
    name: NcName,
    @compactDict
    classes: Map[String, ClassDefinition] = Map(),
    title: Option[LocalizedText] = None,
    @named("slots")
    @compactDict
    slotDefinitions: Map[String, SlotDefinition] = Map(),
    description: Option[LocalizedText] = None,
    @compactDict
    enums: Map[String, EnumDefinition] = Map(),
    @compactDict
    types: Map[String, TypeDefinition] = Map(),
    @compactDict
    subsets: Map[String, SubsetDefinition] = Map(),
    @simpleDict
    prefixes: Map[String, Prefix] = Map(),
    @named("default_prefix")
    defaultPrefix: Option[String] = None,
    @named("default_range")
    defaultRange: Option[Reference[TypeDefinition]] = None,
    @simpleDict
    settings: Map[String, Setting] = Map(),
    imports: Seq[UriOrCurie] = Seq(),
    license: Option[String] = None,
    rank: Option[Int] = None,
    aliases: Seq[LocalizedText] = Seq(),
    @named("alt_descriptions")
    @simpleDict
    altDescriptions: Map[String, AltDescription] = Map(),
    @simpleDict
    annotations: Map[String, Annotation] = Map(),
    bindings: Seq[EnumBinding] = Seq(),
    @named("broad_mappings")
    broadMappings: Seq[UriOrCurie] = Seq(),
    categories: Seq[UriOrCurie] = Seq(),
    @named("close_mappings")
    closeMappings: Seq[UriOrCurie] = Seq(),
    comments: Seq[LocalizedText] = Seq(),
    @named("conforms_to")
    conformsTo: Option[String] = None,
    contributors: Seq[UriOrCurie] = Seq(),
    @named("created_by")
    createdBy: Option[UriOrCurie] = None,
    @named("created_on")
    createdOn: Option[LinkmlDateTime] = None,
    @named("default_curi_maps")
    defaultCuriMaps: Seq[String] = Seq(),
    @named("definition_uri")
    definitionUri: Option[UriOrCurie] = None,
    deprecated: Option[LocalizedText] = None,
    @named("deprecated_element_has_exact_replacement")
    deprecatedElementHasExactReplacement: Option[UriOrCurie] = None,
    @named("deprecated_element_has_possible_replacement")
    deprecatedElementHasPossibleReplacement: Option[UriOrCurie] = None,
    @named("emit_prefixes")
    emitPrefixes: Seq[NcName] = Seq(),
    @named("exact_mappings")
    exactMappings: Seq[UriOrCurie] = Seq(),
    examples: Seq[Example] = Seq(),
    @simpleDict
    extensions: Map[String, ExtensionImpl] = Map(),
    @named("from_schema")
    fromSchema: Option[Uri] = None,
    @named("generation_date")
    generationDate: Option[LinkmlDateTime] = None,
    @named("id_prefixes")
    idPrefixes: Seq[NcName] = Seq(),
    @named("id_prefixes_are_closed")
    idPrefixesAreClosed: Boolean = false,
    implements: Seq[UriOrCurie] = Seq(),
    @named("imported_from")
    importedFrom: Option[String] = None,
    @named("in_language")
    inLanguage: Option[String] = None,
    @named("in_subset")
    inSubset: Seq[Reference[SubsetDefinition]] = Seq(),
    instantiates: Seq[UriOrCurie] = Seq(),
    keywords: Seq[LocalizedText] = Seq(),
    @named("last_updated_on")
    lastUpdatedOn: Option[LinkmlDateTime] = None,
    @named("local_names")
    @simpleDict
    localNames: Map[String, LocalName] = Map(),
    mappings: Seq[UriOrCurie] = Seq(),
    @named("metamodel_version")
    metamodelVersion: Option[String] = None,
    @named("modified_by")
    modifiedBy: Option[UriOrCurie] = None,
    @named("narrow_mappings")
    narrowMappings: Seq[UriOrCurie] = Seq(),
    notes: Seq[LocalizedText] = Seq(),
    @named("related_mappings")
    relatedMappings: Seq[UriOrCurie] = Seq(),
    @named("see_also")
    seeAlso: Seq[UriOrCurie] = Seq(),
    @named("slot_names_unique")
    slotNamesUnique: Boolean = false,
    source: Option[UriOrCurie] = None,
    @named("source_file")
    sourceFile: Option[String] = None,
    @named("source_file_date")
    sourceFileDate: Option[LinkmlDateTime] = None,
    @named("source_file_size")
    sourceFileSize: Option[Int] = None,
    status: Option[UriOrCurie] = None,
    @named("structured_aliases")
    structuredAliases: Seq[StructuredAlias] = Seq(),
    todos: Seq[String] = Seq(),
    version: Option[String] = None,
) extends Element {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): SchemaDefinition =
    this
}
