// Generated by LinkML-Scala from https://w3id.org/linkml/meta
// DO NOT EDIT.

package eu.neverblink.linkml.metamodel

import eu.neverblink.linkml.runtime.*

/** Assignment of a key to a value
  *
  * @param settingKey
  *   The variable name for a setting
  * @param settingValue
  *   The value assigned for a setting
  * @see
  *   From schema: https://w3id.org/linkml/meta
  */
final case class Setting(
    @id
    @named("setting_key")
    settingKey: NcName,
    @value
    @named("setting_value")
    settingValue: String,
) {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  def infer(): Setting =
    this
}
