// Generated by LinkML-Scala from https://w3id.org/linkml/meta
// DO NOT EDIT.

package eu.neverblink.linkml.metamodel

import eu.neverblink.linkml.runtime.*

/** An element that describes how instances are related to other instances
  *
  * @param name
  *   The unique name of the element within the context of the schema. Name is combined with the
  *   default prefix to form the globally unique subject of the target class.
  * @param slotUri
  *   URI of the class that provides a semantic interpretation of the slot in a linked data context.
  *   The URI may come from any namespace and may be shared between schemas.
  * @param title
  *   A concise human-readable display label for the element. The title should mirror the name, and
  *   should use ordinary textual punctuation.
  * @param description
  *   A textual description of the element's purpose and use
  * @param identifier
  *   True means that the slot is the identifier slot of its class. Such a slot uniquely identifies
  *   instances of the class throughout an entire document, meaning there cannot be two (or more)
  *   instances of the class (or instances of any of its descendants) with the same value for the
  *   identifier slot anywhere in the document.
  * @param alias
  *   The alternative name to be used in serializations of an instance instead of the canonical
  *   name.
  * @param multivalued
  *   True means that slot can have more than one value and should be represented using a list or
  *   collection structure.
  * @param required
  *   True means that the slot must be present in instances of the class definition
  * @param recommended
  *   True means that the slot should be present in instances of the class definition, but this is
  *   not required
  * @param isA
  *   A primary parent slot from which inheritable metaslots are propagated
  * @param mixins
  *   A collection of secondary parent mixin slots from which inheritable metaslots are propagated
  * @param inlined
  *   True means that keyed or identified slot appears in an outer structure by value. False means
  *   that only the key or identifier for the slot appears within the domain, referencing a
  *   structure that appears elsewhere.
  * @param inlinedAsList
  *   True means that an inlined slot is represented as a list of range instances. False means that
  *   an inlined slot is represented as a dictionary, whose key is the slot key or identifier and
  *   whose value is the range instance.
  * @param pattern
  *   The string value of the slot must conform to this regular expression expressed in the string
  * @param rank
  *   The relative order in which the element occurs, lower values are given precedence
  * @param anyOf
  *   Holds if at least one of the expressions hold
  * @param exactlyOneOf
  *   Holds if only one of the expressions hold
  * @param noneOf
  *   Holds if none of the expressions hold
  * @param allOf
  *   Holds if all of the expressions hold
  * @param `abstract`
  *   Indicates the class or slot cannot be directly instantiated and is intended for grouping
  *   purposes.
  * @param aliases
  *   Alternate names/labels for the element. These do not alter the semantics of the schema, but
  *   may be useful to support search and alignment.
  * @param allMembers
  *   The value of the slot is multivalued with all members satisfying the condition
  * @param altDescriptions
  *   A sourced alternative description for an element
  * @param annotations
  *   A collection of tag/text tuples with the semantics of OWL Annotation
  * @param applyTo
  *   Used to extend class or slot definitions. For example, if we have a core schema where a gene
  *   has two slots for identifier and symbol, and we have a specialized schema for my_organism
  *   where we wish to add a slot systematic_name, we can avoid subclassing by defining a class
  *   gene_my_organism, adding the slot to this class, and then adding an apply_to pointing to the
  *   gene class. The new slot will be 'injected into' the gene class.
  * @param array
  *   Coerces the value of the slot into an array and defines the dimensions of that array
  * @param asymmetric
  *   If s is antisymmetric, and i.s=v where i is different from v, v.s cannot have value i
  * @param bindings
  *   A collection of enum bindings that specify how a slot can be bound to a permissible value from
  *   an enumeration. LinkML provides enums to allow string values to be restricted to one of a set
  *   of permissible values (specified statically or dynamically). Enum bindings allow enums to be
  *   bound to any object, including complex nested objects. For example, given a (generic) class
  *   Concept with slots id and label, it may be desirable to restrict the values the id takes on in
  *   a given context. For example, a HumanSample class may have a slot for representing sample
  *   site, with a range of concept, but the values of that slot may be restricted to concepts from
  *   a particular branch of an anatomy ontology.
  * @param broadMappings
  *   A list of terms from different schemas or terminology systems that have broader meaning.
  * @param categories
  *   Controlled terms used to categorize an element.
  * @param childrenAreMutuallyDisjoint
  *   If true then all direct is_a children are mutually disjoint and share no instances in common
  * @param closeMappings
  *   A list of terms from different schemas or terminology systems that have close meaning.
  * @param comments
  *   Notes and comments about an element intended primarily for external consumption
  * @param conformsTo
  *   An established standard to which the element conforms.
  * @param contributors
  *   Agent that contributed to the element
  * @param createdBy
  *   Agent that created the element
  * @param createdOn
  *   Time at which the element was created
  * @param definitionUri
  *   The native URI of the element. This is always within the namespace of the containing schema.
  *   Contrast with the assigned URI, via class_uri or slot_uri
  * @param deprecated
  *   Description of why and when this element will no longer be used
  * @param deprecatedElementHasExactReplacement
  *   When an element is deprecated, it can be automatically replaced by this uri or curie
  * @param deprecatedElementHasPossibleReplacement
  *   When an element is deprecated, it can be potentially replaced by this uri or curie
  * @param designatesType
  *   True means that the key slot(s) is used to determine the instantiation (types) relation
  *   between objects and a ClassDefinition
  * @param disjointWith
  *   Two classes are disjoint if they have no instances in common, two slots are disjoint if they
  *   can never hold between the same two instances
  * @param domain
  *   Defines the type of the subject of the slot. Given the following slot definition S1: domain:
  *   C1 range: C2 the declaration X: S1: Y
  *
  * implicitly asserts that X is an instance of C1
  *
  * @param domainOf
  *   The class(es) that reference the slot in a "slots" or "slot_usage" context
  * @param enumRange
  *   An inlined enumeration
  * @param equalsExpression
  *   The value of the slot must equal the value of the evaluated expression
  * @param equalsNumber
  *   The slot must have range of a number and the value of the slot must equal the specified value
  * @param equalsString
  *   The slot must have range string and the value of the slot must equal the specified value
  * @param equalsStringIn
  *   The slot must have range string and the value of the slot must equal one of the specified
  *   values
  * @param exactCardinality
  *   The exact number of entries for a multivalued slot
  * @param exactMappings
  *   A list of terms from different schemas or terminology systems that have identical meaning.
  * @param examples
  *   Example usages of an element
  * @param extensions
  *   A tag/text tuple attached to an arbitrary element
  * @param fromSchema
  *   Id of the schema that defined the element
  * @param hasMember
  *   The value of the slot is multivalued with at least one member satisfying the condition
  * @param idPrefixes
  *   An allowed list of prefixes for which identifiers must conform. The identifier of this class
  *   or slot must begin with the URIs referenced by this prefix
  * @param idPrefixesAreClosed
  *   If true, then the id_prefixes slot is treated as being closed, and any use of an id that does
  *   not have this prefix is considered a violation.
  * @param ifabsent
  *   Function that provides a default value for the slot. * [Tt]rue -- boolean True * [Ff]alse --
  *   boolean False * bnode -- blank node identifier * class_curie -- CURIE for the containing class
  *   * class_uri -- URI for the containing class * default_ns -- schema default namespace *
  *   default_range -- schema default range * int(value) -- integer value * slot_uri -- URI for the
  *   slot * slot_curie -- CURIE for the slot * string(value) -- string value *
  *   EnumName(PermissibleValue) -- enum value
  * @param implements
  *   An element in another schema which this element conforms to. The referenced element is not
  *   imported into the schema for the implementing element. However, the referenced schema may be
  *   used to check conformance of the implementing element.
  * @param implicitPrefix
  *   Causes the slot value to be interpreted as a uriorcurie after prefixing with this string
  * @param importedFrom
  *   The imports entry that this element was derived from. Empty means primary source
  * @param inLanguage
  *   The primary language used in the sources
  * @param inSubset
  *   Used to indicate membership of a term in a defined subset of terms used for a particular
  *   domain or application.
  * @param inherited
  *   True means that the *value* of a slot is inherited by subclasses
  * @param instantiates
  *   An element in another schema which this element instantiates.
  * @param inverse
  *   Indicates that any instance of d s r implies that there is also an instance of r s' d
  * @param irreflexive
  *   If s is irreflexive, then there exists no i such i.s=i
  * @param isClassField
  *   Indicates that for any instance, i, the domain of this slot will include an assertion of i s
  *   range
  * @param isGroupingSlot
  *   True if this slot is a grouping slot
  * @param isUsageSlot
  *   True means that this slot was defined in a slot_usage situation
  * @param key
  *   True means that the slot is the "singular unique key" (also known more simply as the "key
  *   slot") of its class. Such a slot uniquely identifies instances of the class within a single
  *   container, meaning there cannot be two (or more) instances of the class (or instances of any
  *   of its descendants) with the same value for the key slot within the container.
  * @param keywords
  *   Keywords or tags used to describe the element
  * @param lastUpdatedOn
  *   Time at which the element was last updated
  * @param listElementsOrdered
  *   If True, then the order of elements of a multivalued slot is guaranteed to be preserved. If
  *   False, the order may still be preserved but this is not guaranteed
  * @param listElementsUnique
  *   If True, then there must be no duplicates in the elements of a multivalued slot
  * @param locallyReflexive
  *   If s is locally_reflexive, then i.s=i for all instances i where s is a class slot for the type
  *   of i
  * @param mappings
  *   A list of terms from different schemas or terminology systems that have comparable meaning.
  *   These may include terms that are precisely equivalent, broader or narrower in meaning, or
  *   otherwise semantically related but not equivalent from a strict ontological perspective.
  * @param maximumCardinality
  *   The maximum number of entries for a multivalued slot
  * @param maximumValue
  *   For ordinal ranges, the value must be equal to or lower than this
  * @param minimumCardinality
  *   The minimum number of entries for a multivalued slot
  * @param minimumValue
  *   For ordinal ranges, the value must be equal to or higher than this
  * @param mixin
  *   Indicates the class or slot is intended to be inherited from without being an is_a parent.
  *   mixins should not be inherited from using is_a, except by other mixins.
  * @param modifiedBy
  *   Agent that modified the element
  * @param narrowMappings
  *   A list of terms from different schemas or terminology systems that have narrower meaning.
  * @param notes
  *   Editorial notes about an element intended primarily for internal consumption
  * @param owner
  *   The "owner" of the slot. It is the class if it appears in the slots list, otherwise the
  *   declaring slot
  * @param pathRule
  *   A rule for inferring a slot assignment based on evaluating a path through a sequence of slot
  *   assignments
  * @param range
  *   Defines the type of the object of the slot. Given the following slot definition S1: domain: C1
  *   range: C2 the declaration X: S1: Y
  *
  * implicitly asserts Y is an instance of C2
  *
  * @param rangeExpression
  *   A range that is described as a boolean expression combining existing ranges
  * @param readonly
  *   If present, slot is read only. Text explains why
  * @param reflexive
  *   If s is reflexive, then i.s=i for all instances i
  * @param reflexiveTransitiveFormOf
  *   Transitive_form_of including the reflexive case
  * @param relatedMappings
  *   A list of terms from different schemas or terminology systems that have related meaning.
  * @param relationalRole
  *   The role a slot on a relationship class plays, for example, the subject, object or predicate
  *   roles
  * @param role
  *   A textual descriptor that indicates the role played by the slot range
  * @param seeAlso
  *   A list of related entities or URLs that may be of relevance
  * @param shared
  *   If True, then the relationship between the slot domain and range is many to one or many to
  *   many
  * @param singularName
  *   A name that is used in the singular form
  * @param slotGroup
  *   Allows for grouping of related slots into a grouping slot that serves the role of a group
  * @param source
  *   A related resource from which the element is derived.
  * @param status
  *   Status of the element
  * @param stringSerialization
  *   Used on a slot that stores the string serialization of the containing object. The syntax
  *   follows python formatted strings, with slot names enclosed in {}s. These are expanded using
  *   the values of those slots. We call the slot with the serialization the s-slot, the slots used
  *   in the {}s are v-slots. If both s-slots and v-slots are populated on an object then the value
  *   of the s-slot should correspond to the expansion. Implementations of frameworks may choose to
  *   use this property to either (a) PARSE: implement automated normalizations by parsing
  *   denormalized strings into complex objects (b) GENERATE: implement automated to_string labeling
  *   of complex objects For example, a Measurement class may have 3 fields: unit, value, and
  *   string_value. The string_value slot may have a string_serialization of {value}{unit} such that
  *   if unit=cm and value=2, the value of string_value shouldd be 2cm
  * @param structuredAliases
  *   A list of structured_alias objects, used to provide aliases in conjunction with additional
  *   metadata.
  * @param structuredPattern
  *   The string value of the slot must conform to the regular expression in the pattern expression
  * @param subpropertyOf
  *   Ontology property which this slot is a subproperty of. Note: setting this property on a slot
  *   does not guarantee an expansion of the ontological hierarchy into an enumerated list of
  *   possible values in every serialization of the model.
  * @param symmetric
  *   If s is symmetric, and i.s=v, then v.s=i
  * @param todos
  *   Outstanding issues that needs resolution
  * @param transitive
  *   If s is transitive, and i.s=z, and s.s=j, then i.s=j
  * @param transitiveFormOf
  *   If s transitive_form_of d, then (1) s holds whenever d holds (2) s is transitive (3) d holds
  *   whenever s holds and there are no intermediates, and s is not reflexive
  * @param typeMappings
  *   A collection of type mappings that specify how a slot's range should be mapped or serialized
  *   in different frameworks
  * @param unionOf
  *   Indicates that the domain element consists exactly of the members of the element in the range.
  * @param unit
  *   An encoding of a unit
  * @param usageSlotName
  *   The name of the slot referenced in the slot_usage
  * @param valuePresence
  *   If PRESENT then a value must be present (for lists there must be at least one value). If
  *   ABSENT then a value must be absent (for lists, must be empty)
  * @param valuesFrom
  *   The identifier of a "value set" -- a set of identifiers that form the possible values for the
  *   range of a slot. Note: this is different than 'subproperty_of' in that 'subproperty_of' is
  *   intended to be a single ontology term while 'values_from' is the identifier of an entire value
  *   set. Additionally, this is different than an enumeration in that in an enumeration, the values
  *   of the enumeration are listed directly in the model itself. Setting this property on a slot
  *   does not guarantee an expansion of the ontological hierarchy into an enumerated list of
  *   possible values in every serialization of the model.
  * @see
  *   Aliases: slot, field, property, attribute, column, variable
  * @see
  *   From schema: https://w3id.org/linkml/meta
  */
final case class SlotDefinition(
    @id
    name: String,
    @named("slot_uri")
    slotUri: Option[UriOrCurie] = None,
    title: Option[LocalizedText] = None,
    description: Option[LocalizedText] = None,
    identifier: Boolean = false,
    alias: Option[String] = None,
    multivalued: Boolean = false,
    required: Boolean = false,
    recommended: Boolean = false,
    @named("is_a")
    isA: Option[Reference[SlotDefinition]] = None,
    mixins: Seq[Reference[SlotDefinition]] = Seq(),
    inlined: Boolean = false,
    @named("inlined_as_list")
    inlinedAsList: Boolean = false,
    pattern: Option[String] = None,
    rank: Option[Int] = None,
    @named("any_of")
    anyOf: Seq[AnonymousSlotExpression] = Seq(),
    @named("exactly_one_of")
    exactlyOneOf: Seq[AnonymousSlotExpression] = Seq(),
    @named("none_of")
    noneOf: Seq[AnonymousSlotExpression] = Seq(),
    @named("all_of")
    allOf: Seq[AnonymousSlotExpression] = Seq(),
    @named("abstract")
    `abstract`: Boolean = false,
    aliases: Seq[LocalizedText] = Seq(),
    @named("all_members")
    allMembers: Option[AnonymousSlotExpression] = None,
    @named("alt_descriptions")
    @simpleDict
    altDescriptions: Map[String, AltDescription] = Map(),
    @simpleDict
    annotations: Map[String, Annotation] = Map(),
    @named("apply_to")
    applyTo: Seq[Reference[SlotDefinition]] = Seq(),
    array: Option[ArrayExpression] = None,
    asymmetric: Boolean = false,
    bindings: Seq[EnumBinding] = Seq(),
    @named("broad_mappings")
    broadMappings: Seq[UriOrCurie] = Seq(),
    categories: Seq[UriOrCurie] = Seq(),
    @named("children_are_mutually_disjoint")
    childrenAreMutuallyDisjoint: Boolean = false,
    @named("close_mappings")
    closeMappings: Seq[UriOrCurie] = Seq(),
    comments: Seq[LocalizedText] = Seq(),
    @named("conforms_to")
    conformsTo: Option[String] = None,
    contributors: Seq[UriOrCurie] = Seq(),
    @named("created_by")
    createdBy: Option[UriOrCurie] = None,
    @named("created_on")
    createdOn: Option[LinkmlDateTime] = None,
    @named("definition_uri")
    definitionUri: Option[UriOrCurie] = None,
    deprecated: Option[LocalizedText] = None,
    @named("deprecated_element_has_exact_replacement")
    deprecatedElementHasExactReplacement: Option[UriOrCurie] = None,
    @named("deprecated_element_has_possible_replacement")
    deprecatedElementHasPossibleReplacement: Option[UriOrCurie] = None,
    @named("designates_type")
    designatesType: Boolean = false,
    @named("disjoint_with")
    disjointWith: Seq[Reference[SlotDefinition]] = Seq(),
    domain: Option[Reference[ClassDefinition]] = None,
    @named("domain_of")
    domainOf: Seq[Reference[ClassDefinition]] = Seq(),
    @named("enum_range")
    enumRange: Option[EnumExpressionImpl] = None,
    @named("equals_expression")
    equalsExpression: Option[String] = None,
    @named("equals_number")
    equalsNumber: Option[Int] = None,
    @named("equals_string")
    equalsString: Option[String] = None,
    @named("equals_string_in")
    equalsStringIn: Seq[String] = Seq(),
    @named("exact_cardinality")
    exactCardinality: Option[Int] = None,
    @named("exact_mappings")
    exactMappings: Seq[UriOrCurie] = Seq(),
    examples: Seq[Example] = Seq(),
    @simpleDict
    extensions: Map[String, ExtensionImpl] = Map(),
    @named("from_schema")
    fromSchema: Option[Uri] = None,
    @named("has_member")
    hasMember: Option[AnonymousSlotExpression] = None,
    @named("id_prefixes")
    idPrefixes: Seq[NcName] = Seq(),
    @named("id_prefixes_are_closed")
    idPrefixesAreClosed: Boolean = false,
    ifabsent: Option[String] = None,
    implements: Seq[UriOrCurie] = Seq(),
    @named("implicit_prefix")
    implicitPrefix: Option[String] = None,
    @named("imported_from")
    importedFrom: Option[String] = None,
    @named("in_language")
    inLanguage: Option[String] = None,
    @named("in_subset")
    inSubset: Seq[Reference[SubsetDefinition]] = Seq(),
    inherited: Boolean = false,
    instantiates: Seq[UriOrCurie] = Seq(),
    inverse: Option[Reference[SlotDefinition]] = None,
    irreflexive: Boolean = false,
    @named("is_class_field")
    isClassField: Boolean = false,
    @named("is_grouping_slot")
    isGroupingSlot: Boolean = false,
    @named("is_usage_slot")
    isUsageSlot: Boolean = false,
    key: Boolean = false,
    keywords: Seq[LocalizedText] = Seq(),
    @named("last_updated_on")
    lastUpdatedOn: Option[LinkmlDateTime] = None,
    @named("list_elements_ordered")
    listElementsOrdered: Boolean = false,
    @named("list_elements_unique")
    listElementsUnique: Boolean = false,
    @named("local_names")
    @simpleDict
    localNames: Map[String, LocalName] = Map(),
    @named("locally_reflexive")
    locallyReflexive: Boolean = false,
    mappings: Seq[UriOrCurie] = Seq(),
    @named("maximum_cardinality")
    maximumCardinality: Option[Int] = None,
    @named("maximum_value")
    maximumValue: Option[LinkmlAny] = None,
    @named("minimum_cardinality")
    minimumCardinality: Option[Int] = None,
    @named("minimum_value")
    minimumValue: Option[LinkmlAny] = None,
    mixin: Boolean = false,
    @named("modified_by")
    modifiedBy: Option[UriOrCurie] = None,
    @named("narrow_mappings")
    narrowMappings: Seq[UriOrCurie] = Seq(),
    notes: Seq[LocalizedText] = Seq(),
    owner: Option[Reference[Definition]] = None,
    @named("path_rule")
    pathRule: Option[PathExpression] = None,
    range: Option[Reference[Element]] = None,
    @named("range_expression")
    rangeExpression: Option[AnonymousClassExpression] = None,
    readonly: Option[String] = None,
    reflexive: Boolean = false,
    @named("reflexive_transitive_form_of")
    reflexiveTransitiveFormOf: Option[Reference[SlotDefinition]] = None,
    @named("related_mappings")
    relatedMappings: Seq[UriOrCurie] = Seq(),
    @named("relational_role")
    relationalRole: Option[RelationalRoleEnum] = None,
    role: Option[String] = None,
    @named("see_also")
    seeAlso: Seq[UriOrCurie] = Seq(),
    shared: Boolean = false,
    @named("singular_name")
    singularName: Option[String] = None,
    @named("slot_group")
    slotGroup: Option[Reference[SlotDefinition]] = None,
    source: Option[UriOrCurie] = None,
    status: Option[UriOrCurie] = None,
    @named("string_serialization")
    stringSerialization: Option[String] = None,
    @named("structured_aliases")
    structuredAliases: Seq[StructuredAlias] = Seq(),
    @named("structured_pattern")
    structuredPattern: Option[PatternExpression] = None,
    @named("subproperty_of")
    subpropertyOf: Option[Reference[SlotDefinition]] = None,
    symmetric: Boolean = false,
    todos: Seq[String] = Seq(),
    transitive: Boolean = false,
    @named("transitive_form_of")
    transitiveFormOf: Option[Reference[SlotDefinition]] = None,
    @named("type_mappings")
    @compactDict
    typeMappings: Map[String, TypeMapping] = Map(),
    @named("union_of")
    unionOf: Seq[Reference[SlotDefinition]] = Seq(),
    unit: Option[UnitOfMeasure] = None,
    @named("usage_slot_name")
    usageSlotName: Option[String] = None,
    @named("value_presence")
    valuePresence: Option[PresenceEnum] = None,
    @named("values_from")
    valuesFrom: Seq[UriOrCurie] = Seq(),
) extends Definition,
      SlotExpression {

  /** Unfolded slot combining procedure `for metaslot in metaslots` from the spec. This variant
    * merges ALL SlotDefinition slots.
    * @see
    *   https://linkml.io/linkml-model/latest/docs/specification/04derived-schemas/#algorithm-combine-slots
    * @param combineRange
    *   Injected range combination function to resolve a circular dependency between metamodel and
    *   schema view
    */
  def combineWith(
      other: SlotDefinition,
      combineRange: (Reference[Element], Reference[Element]) => Reference[Element],
  ): SlotDefinition =
    copy(
      name = combineFallback(this.name, other.name),
      slotUri = combineOption(this.slotUri, other.slotUri, combineFallback),
      title = combineOption(this.title, other.title, combineFallback),
      description = combineOption(this.description, other.description, combineFallback),
      identifier = combineBoolean(this.identifier, other.identifier),
      alias = combineOption(this.alias, other.alias, combineFallback),
      multivalued = combineBoolean(this.multivalued, other.multivalued),
      required = combineBoolean(this.required, other.required),
      recommended = combineBoolean(this.recommended, other.recommended),
      isA = combineOption(this.isA, other.isA, combineFallback),
      mixins = combineSeq(this.mixins, other.mixins),
      inlined = combineBoolean(this.inlined, other.inlined),
      inlinedAsList = combineBoolean(this.inlinedAsList, other.inlinedAsList),
      pattern = combineOption(this.pattern, other.pattern, combinePattern),
      rank = combineOption(this.rank, other.rank, combineFallback),
      anyOf = combineSeq(this.anyOf, other.anyOf),
      exactlyOneOf = combineSeq(this.exactlyOneOf, other.exactlyOneOf),
      noneOf = combineSeq(this.noneOf, other.noneOf),
      allOf = combineSeq(this.allOf, other.allOf),
      `abstract` = combineBoolean(this.`abstract`, other.`abstract`),
      aliases = combineSeq(this.aliases, other.aliases),
      allMembers = combineOption(this.allMembers, other.allMembers, combineFallback),
      altDescriptions = combineMap(this.altDescriptions, other.altDescriptions),
      annotations = combineMap(this.annotations, other.annotations),
      applyTo = combineSeq(this.applyTo, other.applyTo),
      array = combineOption(this.array, other.array, combineFallback),
      asymmetric = combineBoolean(this.asymmetric, other.asymmetric),
      bindings = combineSeq(this.bindings, other.bindings),
      broadMappings = combineSeq(this.broadMappings, other.broadMappings),
      categories = combineSeq(this.categories, other.categories),
      childrenAreMutuallyDisjoint =
        combineBoolean(this.childrenAreMutuallyDisjoint, other.childrenAreMutuallyDisjoint),
      closeMappings = combineSeq(this.closeMappings, other.closeMappings),
      comments = combineSeq(this.comments, other.comments),
      conformsTo = combineOption(this.conformsTo, other.conformsTo, combineFallback),
      contributors = combineSeq(this.contributors, other.contributors),
      createdBy = combineOption(this.createdBy, other.createdBy, combineFallback),
      createdOn = combineOption(this.createdOn, other.createdOn, combineFallback),
      definitionUri = combineOption(this.definitionUri, other.definitionUri, combineFallback),
      deprecated = combineOption(this.deprecated, other.deprecated, combineFallback),
      deprecatedElementHasExactReplacement = combineOption(
        this.deprecatedElementHasExactReplacement,
        other.deprecatedElementHasExactReplacement,
        combineFallback,
      ),
      deprecatedElementHasPossibleReplacement = combineOption(
        this.deprecatedElementHasPossibleReplacement,
        other.deprecatedElementHasPossibleReplacement,
        combineFallback,
      ),
      designatesType = combineBoolean(this.designatesType, other.designatesType),
      disjointWith = combineSeq(this.disjointWith, other.disjointWith),
      domain = combineOption(this.domain, other.domain, combineFallback),
      domainOf = combineSeq(this.domainOf, other.domainOf),
      enumRange = combineOption(this.enumRange, other.enumRange, combineFallback),
      equalsExpression =
        combineOption(this.equalsExpression, other.equalsExpression, combineFallback),
      equalsNumber = combineOption(this.equalsNumber, other.equalsNumber, combineFallback),
      equalsString = combineOption(this.equalsString, other.equalsString, combineFallback),
      equalsStringIn = combineSeq(this.equalsStringIn, other.equalsStringIn),
      exactCardinality =
        combineOption(this.exactCardinality, other.exactCardinality, combineFallback),
      exactMappings = combineSeq(this.exactMappings, other.exactMappings),
      examples = combineSeq(this.examples, other.examples),
      extensions = combineMap(this.extensions, other.extensions),
      fromSchema = combineOption(this.fromSchema, other.fromSchema, combineFallback),
      hasMember = combineOption(this.hasMember, other.hasMember, combineFallback),
      idPrefixes = combineSeq(this.idPrefixes, other.idPrefixes),
      idPrefixesAreClosed = combineBoolean(this.idPrefixesAreClosed, other.idPrefixesAreClosed),
      ifabsent = combineOption(this.ifabsent, other.ifabsent, combineFallback),
      implements = combineSeq(this.implements, other.implements),
      implicitPrefix = combineOption(this.implicitPrefix, other.implicitPrefix, combineFallback),
      importedFrom = combineOption(this.importedFrom, other.importedFrom, combineFallback),
      inLanguage = combineOption(this.inLanguage, other.inLanguage, combineFallback),
      inSubset = combineSeq(this.inSubset, other.inSubset),
      inherited = combineBoolean(this.inherited, other.inherited),
      instantiates = combineSeq(this.instantiates, other.instantiates),
      inverse = combineOption(this.inverse, other.inverse, combineFallback),
      irreflexive = combineBoolean(this.irreflexive, other.irreflexive),
      isClassField = combineBoolean(this.isClassField, other.isClassField),
      isGroupingSlot = combineBoolean(this.isGroupingSlot, other.isGroupingSlot),
      isUsageSlot = combineBoolean(this.isUsageSlot, other.isUsageSlot),
      key = combineBoolean(this.key, other.key),
      keywords = combineSeq(this.keywords, other.keywords),
      lastUpdatedOn = combineOption(this.lastUpdatedOn, other.lastUpdatedOn, combineFallback),
      listElementsOrdered = combineBoolean(this.listElementsOrdered, other.listElementsOrdered),
      listElementsUnique = combineBoolean(this.listElementsUnique, other.listElementsUnique),
      localNames = combineMap(this.localNames, other.localNames),
      locallyReflexive = combineBoolean(this.locallyReflexive, other.locallyReflexive),
      mappings = combineSeq(this.mappings, other.mappings),
      maximumCardinality =
        combineOption(this.maximumCardinality, other.maximumCardinality, combineFallback),
      maximumValue = combineOption(this.maximumValue, other.maximumValue, combineMax),
      minimumCardinality =
        combineOption(this.minimumCardinality, other.minimumCardinality, combineFallback),
      minimumValue = combineOption(this.minimumValue, other.minimumValue, combineMin),
      mixin = combineBoolean(this.mixin, other.mixin),
      modifiedBy = combineOption(this.modifiedBy, other.modifiedBy, combineFallback),
      narrowMappings = combineSeq(this.narrowMappings, other.narrowMappings),
      notes = combineSeq(this.notes, other.notes),
      owner = combineOption(this.owner, other.owner, combineFallback),
      pathRule = combineOption(this.pathRule, other.pathRule, combineFallback),
      range = combineOption(this.range, other.range, combineRange),
      rangeExpression = combineOption(this.rangeExpression, other.rangeExpression, combineFallback),
      readonly = combineOption(this.readonly, other.readonly, combineFallback),
      reflexive = combineBoolean(this.reflexive, other.reflexive),
      reflexiveTransitiveFormOf = combineOption(
        this.reflexiveTransitiveFormOf,
        other.reflexiveTransitiveFormOf,
        combineFallback,
      ),
      relatedMappings = combineSeq(this.relatedMappings, other.relatedMappings),
      relationalRole = combineOption(this.relationalRole, other.relationalRole, combineFallback),
      role = combineOption(this.role, other.role, combineFallback),
      seeAlso = combineSeq(this.seeAlso, other.seeAlso),
      shared = combineBoolean(this.shared, other.shared),
      singularName = combineOption(this.singularName, other.singularName, combineFallback),
      slotGroup = combineOption(this.slotGroup, other.slotGroup, combineFallback),
      source = combineOption(this.source, other.source, combineFallback),
      status = combineOption(this.status, other.status, combineFallback),
      stringSerialization =
        combineOption(this.stringSerialization, other.stringSerialization, combineFallback),
      structuredAliases = combineSeq(this.structuredAliases, other.structuredAliases),
      structuredPattern =
        combineOption(this.structuredPattern, other.structuredPattern, combineFallback),
      subpropertyOf = combineOption(this.subpropertyOf, other.subpropertyOf, combineFallback),
      symmetric = combineBoolean(this.symmetric, other.symmetric),
      todos = combineSeq(this.todos, other.todos),
      transitive = combineBoolean(this.transitive, other.transitive),
      transitiveFormOf =
        combineOption(this.transitiveFormOf, other.transitiveFormOf, combineFallback),
      typeMappings = combineMap(this.typeMappings, other.typeMappings),
      unionOf = combineSeq(this.unionOf, other.unionOf),
      unit = combineOption(this.unit, other.unit, combineFallback),
      usageSlotName = combineOption(this.usageSlotName, other.usageSlotName, combineFallback),
      valuePresence = combineOption(this.valuePresence, other.valuePresence, combineFallback),
      valuesFrom = combineSeq(this.valuesFrom, other.valuesFrom),
    )

  /** Unfolded slot combining procedure `for metaslot in metaslots` from the spec. This variant
    * merges INHERITED SlotDefinition slots only.
    * @see
    *   https://linkml.io/linkml-model/latest/docs/specification/04derived-schemas/#algorithm-combine-slots
    * @param combineRange
    *   Injected range combination function to resolve a circular dependency between metamodel and
    *   schema view
    */
  def combineInherited(
      other: SlotDefinition,
      combineRange: (Reference[Element], Reference[Element]) => Reference[Element],
  ): SlotDefinition =
    copy(
      identifier = combineBoolean(this.identifier, other.identifier),
      multivalued = combineBoolean(this.multivalued, other.multivalued),
      required = combineBoolean(this.required, other.required),
      recommended = combineBoolean(this.recommended, other.recommended),
      inlined = combineBoolean(this.inlined, other.inlined),
      inlinedAsList = combineBoolean(this.inlinedAsList, other.inlinedAsList),
      pattern = combineOption(this.pattern, other.pattern, combinePattern),
      rank = combineOption(this.rank, other.rank, combineFallback),
      array = combineOption(this.array, other.array, combineFallback),
      designatesType = combineBoolean(this.designatesType, other.designatesType),
      domain = combineOption(this.domain, other.domain, combineFallback),
      equalsExpression =
        combineOption(this.equalsExpression, other.equalsExpression, combineFallback),
      equalsNumber = combineOption(this.equalsNumber, other.equalsNumber, combineFallback),
      equalsString = combineOption(this.equalsString, other.equalsString, combineFallback),
      equalsStringIn = combineSeq(this.equalsStringIn, other.equalsStringIn),
      exactCardinality =
        combineOption(this.exactCardinality, other.exactCardinality, combineFallback),
      ifabsent = combineOption(this.ifabsent, other.ifabsent, combineFallback),
      inherited = combineBoolean(this.inherited, other.inherited),
      key = combineBoolean(this.key, other.key),
      listElementsOrdered = combineBoolean(this.listElementsOrdered, other.listElementsOrdered),
      listElementsUnique = combineBoolean(this.listElementsUnique, other.listElementsUnique),
      maximumCardinality =
        combineOption(this.maximumCardinality, other.maximumCardinality, combineFallback),
      maximumValue = combineOption(this.maximumValue, other.maximumValue, combineMax),
      minimumCardinality =
        combineOption(this.minimumCardinality, other.minimumCardinality, combineFallback),
      minimumValue = combineOption(this.minimumValue, other.minimumValue, combineMin),
      range = combineOption(this.range, other.range, combineRange),
      readonly = combineOption(this.readonly, other.readonly, combineFallback),
      relationalRole = combineOption(this.relationalRole, other.relationalRole, combineFallback),
      role = combineOption(this.role, other.role, combineFallback),
      shared = combineBoolean(this.shared, other.shared),
      structuredPattern =
        combineOption(this.structuredPattern, other.structuredPattern, combineFallback),
      valuePresence = combineOption(this.valuePresence, other.valuePresence, combineFallback),
    )

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  override def infer(): SlotDefinition =
    this
}
