// Generated by LinkML-Scala from https://w3id.org/linkml/meta
// DO NOT EDIT.

package eu.neverblink.linkml.metamodel

import eu.neverblink.linkml.runtime.*

/** A unit of measure, or unit, is a particular quantity value that has been chosen as a scale for
  * measuring other quantities the same kind (more generally of equivalent dimension).
  *
  * @param abbreviation
  *   An abbreviation for a unit is a short ASCII string that is used in place of the full name for
  *   the unit in contexts where non-ASCII characters would be problematic, or where using the
  *   abbreviation will enhance readability. When a power of a base unit needs to be expressed, such
  *   as squares this can be done using abbreviations rather than symbols (source: qudt)
  * @param derivation
  *   Expression for deriving this unit from other units
  * @param descriptiveName
  *   The spelled out name of the unit, for example, meter
  * @param exactMappings
  *   Used to link a unit to equivalent concepts in ontologies such as UO, SNOMED, OEM, OBOE, NCIT
  * @param hasQuantityKind
  *   Concept in a vocabulary or ontology that denotes the kind of quantity being measured, e.g.
  *   length
  * @param symbol
  *   Name of the unit encoded as a symbol
  * @param ucumCode
  *   Associates a QUDT unit with its UCUM code (case-sensitive).
  * @see
  *   From schema: https://w3id.org/linkml/units
  */
final case class UnitOfMeasure(
    abbreviation: Option[String] = None,
    derivation: Option[String] = None,
    @named("descriptive_name")
    descriptiveName: Option[String] = None,
    @named("exact_mappings")
    exactMappings: Seq[UriOrCurie] = Seq(),
    @named("has_quantity_kind")
    hasQuantityKind: Option[UriOrCurie] = None,
    @named("iec61360code")
    iec61360Code: Option[String] = None,
    symbol: Option[String] = None,
    @named("ucum_code")
    ucumCode: Option[String] = None,
) {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  def infer(): UnitOfMeasure =
    this
}
