// Generated by LinkML-Scala from https://linkml.neverblink.eu/model/owl-import-config
// DO NOT EDIT.

package eu.neverblink.linkml.generator.owl.config

import eu.neverblink.linkml.runtime.*

/** A prefix and the namespace it stands for.
  *
  * @see
  *   From schema: https://linkml.neverblink.eu/model/owl-import-config
  */
final case class NamespacePrefix(
    @value
    namespace: String,
    @id
    prefix: String,
) {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  def infer(): NamespacePrefix =
    this
}
