// Generated by LinkML-Scala from https://linkml.neverblink.eu/model/owl-import-config
// DO NOT EDIT.

package eu.neverblink.linkml.generator.owl.config

import eu.neverblink.linkml.runtime.*

/** Settings for the OWL importer.
  *
  * @param annotations
  *   Whether to keep annotations that no metaslot uses, as LinkML `annotations`.
  * @param datatypes
  *   LinkML types for datatype IRIs, on top of the built-in XSD and RDF ones.
  * @param defaultPrefix
  *   Prefix of the namespace most of the ontology's terms are in. Detected if not set.
  * @param enumsFromIndividuals
  *   Whether a class that is just a set of named individuals, and is the range of some property,
  *   becomes an enum. A class defined with `owl:oneOf` always does.
  * @param imports
  *   LinkML schemas to import instead of `owl:imports`, keyed by ontology IRI. Other `owl:imports`
  *   are left out with a warning.
  * @param metadata
  *   Annotation properties to read each metaslot from, in order of preference. Replaces the default
  *   list only for the metaslots it lists.
  * @param multivalued
  *   Whether slots are multivalued unless the property is functional. On by default, because OWL
  *   allows any number of values.
  * @param name
  *   The schema `name`. Defaults to the ontology's `rdfs:label` if it is a valid name, else the
  *   default prefix.
  * @param naming
  *   How names are made from IRIs.
  * @param prefixes
  *   Extra prefixes, on top of the ones the ontology declares.
  * @param renames
  *   Fixed names for specific terms, keyed by IRI or CURIE.
  * @param schemaId
  *   The schema `id`. Defaults to the ontology IRI.
  * @param someValuesFrom
  *   How to read `owl:someValuesFrom`.
  * @see
  *   From schema: https://linkml.neverblink.eu/model/owl-import-config
  */
final case class OwlImportConfig(
    @serializeDefault
    annotations: Boolean = true,
    @simpleDict
    datatypes: Map[String, DatatypeMapping] = Map(),
    @named("default_prefix")
    defaultPrefix: Option[String] = None,
    @named("enums_from_individuals")
    @serializeDefault
    enumsFromIndividuals: Boolean = true,
    @simpleDict
    imports: Map[String, ImportMapping] = Map(),
    @simpleDict
    metadata: Map[String, MetadataSources] = Map(),
    @serializeDefault
    multivalued: Boolean = true,
    name: Option[String] = None,
    naming: Option[Naming] = None,
    @simpleDict
    prefixes: Map[String, NamespacePrefix] = Map(),
    @simpleDict
    renames: Map[String, TermRename] = Map(),
    @named("schema_id")
    schemaId: Option[String] = None,
    @named("some_values_from")
    @serializeDefault
    someValuesFrom: Option[SomeValuesFrom] = Some(SomeValuesFrom.Required),
) {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  def infer(): OwlImportConfig =
    this
}
