// Generated by LinkML-Scala from https://linkml.neverblink.eu/model/owl-import-config
// DO NOT EDIT.

package eu.neverblink.linkml.generator.owl.config

import eu.neverblink.linkml.runtime.*

/** A fixed name for a term.
  *
  * @param term
  *   The term's IRI or CURIE.
  * @see
  *   From schema: https://linkml.neverblink.eu/model/owl-import-config
  */
final case class TermRename(
    @value
    @named("new_name")
    newName: String,
    @id
    term: String,
) {

  /** Fill in the slots that have an `equals_expression` with their computed values, and check that
    * the values already present agree with what their expressions infer.
    *
    * @throws eu.neverblink.linkml.runtime.InferenceException
    *   if a slot's value contradicts the value inferred for it, or if an expression references a
    *   slot that has no value
    */
  def infer(): TermRename =
    this
}
