name: Code checks

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-ci-pr-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  scalafmt-lint:
    name: Scalafmt lint
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Cache dependencies
        uses: coursier/cache-action@v8

      - name: Run scalafmt
        run: ./mill --no-server __.jvm.checkFormat


  scalafix-lint:
    name: Scalafix lint
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Cache dependencies
        uses: coursier/cache-action@v8

      - name: Run scalafix
        run: ./mill --no-server __.jvm.fix --check

  git-lint:
    name: Git lint
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    defaults:
      run:
        shell: bash
    steps:
      # Searches the code for the issue tag, so we don't have stranded issue tags
      # Given a branch name like `LNK-1/make-the-repo`, this job will fail
      # if there is a `TODO LNK-1` somewhere in the code
      #
      # This has to assume that the branch name is either the issue tag like `LNK-1/issue-slug`
      # Or a personal/hotfix branch like `kacper/some-fix` or `hotfix/for-parsing`
      # Also allows bare branch names like `LNK-1`.
      - name: Ensure correct branch name and search for the
        run: |
          ID=$(echo $GITHUB_HEAD_REF | cut -f 1 -d "/")
          echo $ID | grep -E "^([A-Z]+-[0-9]+)|([a-z0-9]+)$" \
            || (echo "Bad branch name: $ID"; false) \
            && ! grep -r --exclude-dir ".*" --exclude-dir out "$ID"